### ISSUE TITLE
Error "undefined applications" produced depending on dependency order

### ISSUE THREAD

**Issue by prook** [bitwalker/distillery#500] opened 2018-08-23 09:26 UTC
### Steps to reproduce

1. `mix new test_dep`
2. `mix new test_app`
3. In `test_dep`, add a `runtime: false` dependency, e. g. `elixir_make`:

```elixir
  defp deps do
    [
      {:elixir_make, "~> 0.4", runtime: false},
    ]
  end
```
4. In `test_app`, add `distillery`, any hex dependency, that transitively uses `elixir_make`, such as `elixir_ale`, and `test_dep`:
```elixir
  defp deps do
    [
      {:distillery, "~> 2.0", runtime: false},
      {:elixir_ale, "~> 1.1"},
      {:test_dep, path: "../test_dep"},
    ]
  end
```
5. In `test_app`, run `mix do deps.get, release.init`.
6. In `test_app`, run `mix release`. Verbose output follows:

<summary>
  <details>

```
==> Loading configuration..
==> Assembling release..
==> Building release test_main:0.1.0 using environment dev
==> Discovered applications:
  > kernel-6.0
  |
  |  from: /usr/lib/erlang/lib/kernel-6.0
  |  applications: none
  |  includes: none
  |_____

  > stdlib-3.5
  |
  |  from: /usr/lib/erlang/lib/stdlib-3.5
  |  applications:
  |      :kernel
  |  includes: none
  |_____

  > compiler-7.2
  |
  |  from: /usr/lib/erlang/lib/compiler-7.2
  |  applications:
  |      :kernel
  |      :stdlib
  |  includes: none
  |_____

  > elixir-1.7.2
  |
  |  from: /usr/local/lib/elixir/bin/../lib/elixir
  |  applications:
  |      :kernel
  |      :stdlib
  |      :compiler
  |  includes: none
  |_____

  > iex-1.7.2
  |
  |  from: /usr/local/lib/elixir/bin/../lib/iex
  |  applications:
  |      :kernel
  |      :stdlib
  |      :elixir
  |  includes: none
  |_____

  > mix-1.7.2
  |
  |  from: /usr/local/lib/elixir/bin/../lib/mix
  |  applications:
  |      :kernel
  |      :stdlib
  |      :elixir
  |  includes: none
  |_____

  > sasl-3.2
  |
  |  from: /usr/lib/erlang/lib/sasl-3.2
  |  applications:
  |      :kernel
  |      :stdlib
  |  includes: none
  |_____

  > runtime_tools-1.13
  |
  |  from: /usr/lib/erlang/lib/runtime_tools-1.13
  |  applications:
  |      :kernel
  |      :stdlib
  |  includes: none
  |_____

  > logger-1.7.2
  |
  |  from: /usr/local/lib/elixir/bin/../lib/logger
  |  applications:
  |      :kernel
  |      :stdlib
  |      :elixir
  |  includes: none
  |_____

  > artificery-0.2.6
  |
  |  from: _build/dev/lib/artificery
  |  applications:
  |      :kernel
  |      :stdlib
  |      :elixir
  |  includes: none
  |_____

  > distillery-2.0.4
  |
  |  from: _build/dev/lib/distillery
  |  applications:
  |      :kernel
  |      :stdlib
  |      :elixir
  |      :runtime_tools
  |      :logger
  |      :artificery
  |  includes: none
  |_____

  > elixir_ale-1.1.0
  |
  |  from: _build/dev/lib/elixir_ale
  |  applications:
  |      :kernel### Issue description
  |      :stdlib
  |      :elixir
  |      :elixir_make
  |  includes: none
  |_____

  > test_dep-0.1.0
  |
  |  from: _build/dev/lib/test_dep
  |  applications:
  |      :kernel
  |      :stdlib
  |      :elixir
  |      :logger
  |  includes: none
  |_____

  > test_main-0.1.0
  |
  |  from: _build/dev/lib/test_main
  |  applications:
  |      :kernel
  |      :stdlib
  |      :elixir
  |      :logger
  |      :elixir_ale
  |      :test_dep
  |  includes: none
  |_____

==> Running validation checks..
    > Mix.Releases.Checks.Erts * PASS
    > Mix.Releases.Checks.Cookie * PASS
    > Mix.Releases.Checks.MissingApps * PASS
    > Mix.Releases.Checks.LoadedOrphanedApps * PASS
==> Generated overlay vars:
    release_name=:test_main
    release_version="0.1.0"
    is_upgrade=false
    upgrade_from=:latest
    dev_mode=true
    include_erts=false
    include_src=false
    include_system_libs=false
    erl_opts=""
    run_erl_env=""
    erts_vsn="10.0"
    output_dir="_build/dev/rel/test_main"
==> Copying applications to _build/dev/rel/test_main
==> Generating start_erl.data
==> Generating vm.args
==> Generating sys.config from config/config.exs
==> Generating boot scripts
==> Release failed, during .boot generation:
        Undefined applications: [elixir_make]
```

  </details>
</summary>

### Issue description

With **Elixir 1.7.2** and **Distillery 2.0.4**, the `mix release` fails as shown above.

Interestingly enough, `mix release` succeeds if we swap `elixir_ale` and `test_dep` in `test_app`, i. e.,

```elixir
  defp deps do
    [
      {:distillery, "~> 2.0", runtime: false},
      {:test_dep, path: "../test_dep"}, # :test_dep now comes before :elixir_ale
      {:elixir_ale, "~> 1.1"},
    ]
  end
```

`mix release --verbose` output then looks as follows (note `:elixir_make` is now among discovered applications):

<summary>
  <details>

```
Generated test_main app
==> Loading configuration..
==> Assembling release..
==> Building release test_main:0.1.0 using environment dev
==> Discovered applications:
  > kernel-6.0
  |
  |  from: /usr/lib/erlang/lib/kernel-6.0
  |  applications: none
  |  includes: none
  |_____

  > stdlib-3.5
  |
  |  from: /usr/lib/erlang/lib/stdlib-3.5
  |  applications:
  |      :kernel
  |  includes: none
  |_____

  > compiler-7.2
  |
  |  from: /usr/lib/erlang/lib/compiler-7.2
  |  applications:
  |      :kernel
  |      :stdlib
  |  includes: none
  |_____

  > elixir-1.7.2
  |
  |  from: /usr/local/lib/elixir/bin/../lib/elixir
  |  applications:
  |      :kernel
  |      :stdlib
  |      :compiler
  |  includes: none
  |_____

  > iex-1.7.2
  |
  |  from: /usr/local/lib/elixir/bin/../lib/iex
  |  applications:
  |      :kernel
  |      :stdlib
  |      :elixir
  |  includes: none
  |_____

  > mix-1.7.2
  |
  |  from: /usr/local/lib/elixir/bin/../lib/mix
  |  applications:
  |      :kernel
  |      :stdlib
  |      :elixir
  |  includes: none
  |_____

  > sasl-3.2
  |
  |  from: /usr/lib/erlang/lib/sasl-3.2
  |  applications:
  |      :kernel
  |      :stdlib
  |  includes: none
  |_____

  > runtime_tools-1.13
  |
  |  from: /usr/lib/erlang/lib/runtime_tools-1.13
  |  applications:
  |      :kernel
  |      :stdlib
  |  includes: none
  |_____

  > logger-1.7.2
  |
  |  from: /usr/local/lib/elixir/bin/../lib/logger
  |  applications:
  |      :kernel
  |      :stdlib
  |      :elixir
  |  includes: none
  |_____

  > artificery-0.2.6
  |
  |  from: _build/dev/lib/artificery
  |  applications:
  |      :kernel
  |      :stdlib
  |      :elixir
  |  includes: none
  |_____

  > distillery-2.0.4
  |
  |  from: _build/dev/lib/distillery
  |  applications:
  |      :kernel
  |      :stdlib
  |      :elixir
  |      :runtime_tools
  |      :logger
  |      :artificery
  |  includes: none
  |_____

  > test_dep-0.1.0
  |
  |  from: _build/dev/lib/test_dep
  |  applications:
  |      :kernel
  |      :stdlib
  |      :elixir
  |      :logger
  |  includes: none
  |_____

  > elixir_make-0.4.2
  |
  |  from: _build/dev/lib/elixir_make
  |  applications:
  |      :kernel
  |      :stdlib
  |      :elixir
  |  includes: none
  |_____

  > elixir_ale-1.1.0
  |
  |  from: _build/dev/lib/elixir_ale
  |  applications:
  |      :kernel
  |      :stdlib
  |      :elixir
  |      :elixir_make
  |  includes: none
  |_____

  > test_main-0.1.0
  |
  |  from: _build/dev/lib/test_main
  |  applications:
  |      :kernel
  |      :stdlib
  |      :elixir
  |      :logger
  |      :test_dep
  |      :elixir_ale
  |  includes: none
  |_____

==> Running validation checks..
    > Mix.Releases.Checks.Erts * PASS
    > Mix.Releases.Checks.Cookie * PASS
    > Mix.Releases.Checks.MissingApps * PASS
    > Mix.Releases.Checks.LoadedOrphanedApps * PASS
==> Generated overlay vars:
    release_name=:test_main
    release_version="0.1.0"
    is_upgrade=false
    upgrade_from=:latest
    dev_mode=true
    include_erts=false
    include_src=false
    include_system_libs=false
    erl_opts=""
    run_erl_env=""
    erts_vsn="10.0"
    output_dir="_build/dev/rel/test_main"
==> Copying applications to _build/dev/rel/test_main
==> Generating start_erl.data
==> Generating vm.args
==> Generating sys.config from config/config.exs
==> Generating boot scripts
==> Generating RELEASES
==> Applying overlays
==> Applying mkdir overlay
    dst: releases/0.1.0/hooks
==> Applying mkdir overlay
    dst: releases/0.1.0/hooks/pre_configure.d
==> Applying mkdir overlay
    dst: releases/0.1.0/hooks/post_configure.d
==> Applying mkdir overlay
    dst: releases/0.1.0/hooks/pre_start.d
==> Applying mkdir overlay
    dst: releases/0.1.0/hooks/post_start.d
==> Applying mkdir overlay
    dst: releases/0.1.0/hooks/pre_stop.d
==> Applying mkdir overlay
    dst: releases/0.1.0/hooks/post_stop.d
==> Applying mkdir overlay
    dst: releases/0.1.0/hooks/pre_upgrade.d
==> Applying mkdir overlay
    dst: releases/0.1.0/hooks/post_upgrade.d
==> Applying copy overlay
    src: _build/dev/lib/distillery/priv/libexec
    dst: releases/0.1.0/libexec
==> Applying mkdir overlay
    dst: releases/0.1.0/commands
==> You have set dev_mode to true, skipping archival phase
Release succesfully built!
To start the release you have built, you can use one of the following tasks:

    # start a shell, like 'iex -S mix'
    > _build/dev/rel/test_main/bin/test_main console

    # start in the foreground, like 'mix run --no-halt'
    > _build/dev/rel/test_main/bin/test_main foreground

    # start in the background, must be stopped with the 'stop' command
    > _build/dev/rel/test_main/bin/test_main start

If you started a release elsewhere, and wish to connect to it:

    # connects a local shell to the running node
    > _build/dev/rel/test_main/bin/test_main remote_console

    # connects directly to the running node's console
    > _build/dev/rel/test_main/bin/test_main attach

For a complete listing of commands and their use:

    > _build/dev/rel/test_main/bin/test_main help
```

  </details>
</summary>

It appears the `mix release` fails if a group of dependencies share the same transitive runtime dependency, and the last one of them is declared using `:path`, `:git` or `:github`.

With **Elixir 1.6.6**, `mix release` succeeds regardless of the dependency ordering, but with the following warning:

```
==> Running validation checks..
    > Mix.Releases.Checks.Erts * PASS
    > Mix.Releases.Checks.Cookie * PASS
    > Mix.Releases.Checks.MissingApps * WARN

    > Mix.Releases.Checks.LoadedOrphanedApps * PASS
One or more direct or transitive dependencies are missing from
    :applications or :included_applications, they will not be included
    in the release:

        :elixir_make

    This can cause your application to fail at runtime. If you are sure
    that this is not an issue, you may ignore this warning.
```

**Comment by ConnorRigby** [comment] 2018-08-23 15:33
I also hit this issue. I think it might actually be partially the fault of Elixir/Mix not persisting `runtime: false` up from direct or transitive deps

**Comment by bitwalker** [comment] 2018-08-23 16:09
Yeah, there was a recent change made in Mix regarding this, so it looks like I'll need to address that sooner than I thought.

**Comment by prook** [comment] 2018-08-23 19:44
After looking into the issue some more, I'm now (almost) sure this is not a Distillery issue, but a bug in [Mix.Dep.load_on_environment/1](https://github.com/elixir-lang/elixir/blob/master/lib/mix/lib/mix/dep.ex#L190).

Also, the issue is kind of inverse to what I described. The problem seems to be `elixir_make` not marked as `runtime: false` in the list returned from Mix.Dep.load_on_environment/1, when a `elixir_ale`, i. e., **a hex dependency with transitive `runtime: false` dependency is last in the deps list**. Consequently, `mix release` barfs, because it's been fed junk.

To elaborate, when the dependencies are ordered like this,

```elixir
  {:elixir_ale, "~> 1.1"},
  {:test_dep, path: "../test_dep"},
```

Distillery reports an error, because Mix.Dep.load_on_environment/1 returns (and I think this is right)

```elixir
[
  %Mix.Dep{
    app: :elixir_make,
    # ...snip for brevity
    opts: [
      lock: {:hex, :elixir_make, "0.4.2",
       "332c649d08c18bc1ecc73b1befc68c647136de4f340b548844efc796405743bf",
       [:mix], [], "hexpm"},
      env: :prod,
      repo: "hexpm",
      hex: "elixir_make",
      build: "/tmp/tmp.ncJyP6cP6m/test_main_fail/_build/dev/lib/elixir_make",
      dest: "/tmp/tmp.ncJyP6cP6m/test_main_fail/deps/elixir_make",
      # =========================
      # THIS is the important bit
      # runtime: false is PRESENT
      # =========================
      runtime: false
    ],
    # snip
  },
  # ...snip...
]
```

When ordering the deps other way around, we get this:

```elixir
[
  %Mix.Dep{
    app: :elixir_make,
    # snip
    opts: [
      lock: {:hex, :elixir_make, "0.4.2",
       "332c649d08c18bc1ecc73b1befc68c647136de4f340b548844efc796405743bf",
       [:mix], [], "hexpm"},
      env: :prod,
      build: "/tmp/tmp.ncJyP6cP6m/test_main_ok/_build/dev/lib/elixir_make",
      dest: "/tmp/tmp.ncJyP6cP6m/test_main_ok/deps/elixir_make",
      hex: "elixir_make",
      repo: "hexpm",
      # =========================
      # THIS is the important bit
      # runtime: false is MISSING
      # =========================
      optional: false
    ],
    requirement: "~> 0.4",
    scm: Hex.SCM,
    status: {:ok, "0.4.2"},
    system_env: [],
    top_level: false
  },
  # ...snip...
]
```

When `elixir_make` is not marked `runtime: false`, it later finds its way into `elixir_ale`'s `applications` list in [Mix.Releases.Release.do_apps/3](https://github.com/bitwalker/distillery/blob/master/lib/mix/lib/releases/models/release.ex#L547) because it matches [mix/lib/releases/models/app.ex#L55](https://github.com/bitwalker/distillery/blob/master/lib/mix/lib/releases/models/app.ex:55) instead of [releases/models/app.ex:52](https://github.com/bitwalker/distillery/blob/master/lib/mix/lib/releases/models/app.ex#L52). IMHO, this is a correct behaviour on Distillery's side.

To conclude, the problem most likely lies with [Mix.Dep.load_on_environment](https://github.com/elixir-lang/elixir/blob/master/lib/mix/lib/mix/dep.ex#L190):

1. It does not mark a dependency `runtime: false`, when it actually is.
2. It does return different result for the same dependencies depending on their order.

**Comment by prook** [comment] 2018-08-23 19:48
Ooops, I mistakenly closed the issue. It probably should get closed, but only if my conclusions above are true. Waiting for confirmation.

**Comment by josevalim** [comment] 2018-08-24 16:02
Two notes:

  1. The `runtime: false` is actually not propagated in Hex dependencies, that's why you get conflicting values.

  2. Mix.Dep.load_on_environment is private API and its behaviour may change between releases. We have optimized it on v1.7 so we no longer have to build the dependency graph for every node in the graph but this means information such as `:runtime` does not propagate unless you rebuild the graph at certain moments.

In a nutshell, this means you can't access the dependency graph to figure out stuff like runtime. Partly because sometimes it isn't there when they come from Hex (and this has ALWAYS been a bug) and partly because the graph no longer stores it.

We have effectively fixed both bugs in Elixir master by no longer accessing the runtime information from the dependencies but directly from the mix.exs definition. However, for you to see such errors when building a release on v1.7.2, it makes me think that distillery is building the release based on the Mix.Dep graph and not based on the included_applications/applications graph. Is this the case @bitwalker? What is your source of truth?

The other option is to try Elixir master and see if it works there. If you put a repo that reproduces this on GitHub, I can try master too. If it works on master, we will gladly backport the fix, but I still think Distillery would have false postives warnings on its current implementation (i.e. elixir_make will be marked as runtime: false but distillery can't see it, so it will emit a warning of orphaned apps while it isn't). At this point, you may consider giving up on the warning altogether, as most issues with orphaned apps have been addressed once we added the extra_applications check.

**Comment by bitwalker** [comment] 2018-08-24 16:44
@josevalim Releases are not necessarily the same as Mix projects, so we can't just follow `applications`/`included_applications` from the root project. Instead, you specify the applications which form the "roots" of the release, and we build a graph by traversing the `applications` and `included_applications` lists recursively. We use `Mix.Dep` APIs to embellish the metadata about a particular application, namely, whether or not we should exclude it. We also use the dependency information to figure out if a dependency should be part of the release (because it is either directly or transitively depended upon), but is not present in one of those lists (typically because the list is built by hand, as is the case with Erlang deps). This allows us to warn at build-time that an app may be missing, and that the release will fail if the runtime code depends on that app in some way.

What I'm noticing in 1.7.2 is that even when `runtime: false` is set in the dependency list (`:elixir_ale` for example, has `:elixir_make` as runtime-only), the dependency still ends up in the inferred applications list (e.g. `:elixir_make` shows up as being a runtime dependency of `:elixir_ale` when only considering the applications list, even though that is not what is intended). I'm not sure why `runtime: false` dependencies end up in the inferred applications list - that seems like a bug to me.

Because of this, if I only follow the applications/included_applications lists, then effectively _everything_ gets pulled into the release, which is obviously not desirable. I'm currently reworking the code to check the `mix.exs` of Mix dependencies - but I had hoped that by using the `Mix.Dep` APIs, I could more or less reuse the work Mix was already performing, without reinventing the wheel, knowing that eventually the tooling in core would need to do something similar. The extra maintenance burden on me was worth that tradeoff.

Hopefully that explains a bit better why this issue is present in Distillery - I'm certainly open to suggestions on better ways to solve the problem :).

**Comment by josevalim** [comment] 2018-08-24 17:02
> What I'm noticing in 1.7.2 is that even when runtime: false is set in the dependency list (:elixir_ale for example, has :elixir_make as runtime-only), the dependency still ends up in the inferred applications list (e.g. :elixir_make shows up as being a runtime dependency of :elixir_ale when only considering the applications list, even though that is not what is intended). I'm not sure why runtime: false dependencies end up in the inferred applications list - that seems like a bug to me.

That's because elixir_ale is a hex dependency and the runtime information is not stored for dependencies coming from hex. This is an issue that exists in all Elixir versions, including v1.7.2 and before.

> Because of this, if I only follow the applications/included_applications lists, then effectively everything gets pulled into the release, which is obviously not desirable.

I think you should follow only applications/included_applications anyway and ask the Elixir team (ahem) to fix their bug. Otherwise, it seems that an attempt to work around our bug introduces more bugs and none of them get fixed. :)

**Comment by bitwalker** [comment] 2018-08-24 17:42
@josevalim I don't doubt that the issue exists in previous versions, but to be clear, Distillery's warnings were working (in terms of "working as intended") up until 1.7.2 - i.e. the example release in this issue builds successfully and a warning is generated that `:elixir_make` is excluded because it is marked `runtime: false` when first encountered (in `:test_dep`), but is later found declared as a runtime dependency (in this case, by `:elixir_ale`). I haven't tested to see if changing the order silences the warning because `:elixir_make` is seen as a runtime dependency first, but that is considered fine for these warnings - false positives are allowed, we just don't want false negatives (i.e. "everything is fine" at build-time, then blow up at runtime). 

I also want to assure you that I'm _not_ saying Elixir is at fault for this issue, as reported - I just want to clarify that this has been an important feature, in that it has already been helpful numerous times in solving issues.

I'm happy to open an issue regarding `runtime: false` - though I would like to better understand your perspective on what needs to change there. My own perspective is that Mix currently incorrectly infers the applications list (for dependencies pulled from Hex) - but I'm not sure how that issue needs to be solved. It seems like something Hex needs to propagate, but that's just a guess.

There is also the question of how best to provide the warnings a tool like Distillery needs to provide without being forced to use private APIs. Even if the Elixir team addresses the issue with `runtime: false`, we still want to warn users about non-Mix deps. If someone pulls in an Erlang dep that has an application missing from its applications list, while that app is declared as a dependency, they are going to suffer through some painful troubleshooting at runtime without warnings. Worse, they will assume that Distillery is at fault. The warnings alleviate that by pointing directly to the cause of the issue, but we can only get those warnings by comparing resolved dependencies against the declared applications lists.

**Comment by josevalim** [comment] 2018-08-24 17:59
To clarify, there are two issues here:

1. The one actually reported by @prook where a release fails to build

2. A false positive in the warning, which you said is fine, but it is bound to get worst on v1.7+ because runtime will be even less accurate

Let's ignore 2 for now (I don't want to mix discussions - maybe we can talk about the accuracy of the warning in another issue).

I don't know why 1 happens. My *suspicion*, that has not been confirmed yet, is that this bug would not exist if you were relying only on the applications list to **build** the release. It is totally fine to use Mix.Dep for the warnings, and cross this information to emit the warnings, but the applications/included_applications should be the source of truth.

Does it make sense? What do you think?

> but I'm not sure how that issue needs to be solved. It seems like something Hex needs to propagate, but that's just a guess.

It is already solved in master in that PR that you commented on. :) The secret is to always read the project mix.exs to get the runtime information, completely bypassing Mix.Dep.

**Comment by josevalim** [comment] 2018-08-24 18:45
I followed @prook steps and I was able to reproduce the issue. Indeed, distillery is using the dependency tree (which comes from a private API) [to dictate the applications in the release](https://github.com/bitwalker/distillery/blob/master/lib/mix/lib/releases/models/release.ex#L416). I believe this would be better addressed by using applications/included_applications as the source of truth.

In any case, I will go ahead and release Elixir v1.7.3, as it is probably the shortest way to address this. But I want to point out this is not a healthy situation to be in. I have rang the bells about private APIs elsewhere, so I will save you from having to read it once again. :)

**Comment by bitwalker** [comment] 2018-08-24 20:06
The code you linked doesn't do what you think it does ;). We do use applications/included applications as the source of truth and only use the private API to determine whether to remove applications from the release when marked runtime false. We use dependency information for the warnings as well.

I have a fix for Distillery, so no need to rush your release :)

**Comment by josevalim** [comment] 2018-08-24 20:11
>  only use the private API to determine whether to remove applications from the release when marked runtime false. 

This is exactly what I was referring to. If you use the Mix.Dep to remove entries from the applications list, so for those apps, you consider Mix.Dep as the source of truth. I don't think we should remove apps from the applications list in any circumstance.

In any case, v1.7.3 is out about an hour ago. :)

**Comment by bitwalker** [comment] 2018-08-24 20:52
> I don't think we should remove apps from the applications list in any circumstance

I disagree in this case, it is clear that the applications list is incorrect if the dependency is marked `runtime: false` - when marked this way, the intent (as I've always understood it) is that the dependency will not be used at runtime, and a release is purely a runtime construct. It also implies that Mix itself is doing the wrong thing by not starting those dependencies at runtime, as indicated by the Erlang [manual](http://erlang.org/doc/man/app.html):

> All applications that must be started before this application is allowed to be started. systools uses this list to generate correct start scripts. Defaults to the empty list, but notice that all applications have dependencies to (at least) Kernel and STDLIB.

If the intent is something more akin to setting the application start type to `:load` or `:none`, then that metadata needs to be surfaced in a public API, because it is critical information for building a release. We can't afford to build a release that starts an application that Mix itself doesn't start, when it is explicitly marked "do not start this".

**Comment by josevalim** [comment] 2018-08-24 21:11
> I disagree in this case, it is clear that the applications list is incorrect if the dependency is marked runtime: false - when marked this way, the intent (as I've always understood it) is that the dependency will not be used at runtime

This is a Mix behaviour though. If `:runtime` is false and you have not specified the applications list, then it means Mix won't include those dependencies in the automatically inferred list. Furthermore, if in Mix you do `runtime: false` and you include an app in the application list, then Mix won't remove it. Distillery should just assume that whatever built the .app file has already respected the `:runtime` value.

**Comment by bitwalker** [comment] 2018-08-24 21:51
> This is a Mix behaviour though. If :runtime is false and you have not specified the applications list, then it means Mix won't include those dependencies in the automatically inferred list.

That isn't/wasn't the case though, as demonstrated in the issue here (in 1.7.2 anyway, if that was a bug which is fixed in 1.7.3, then that's perfect, things are gravy for everyone). Specifically that a dependency had declared an application as `runtime: false`, but it still ended up in the applications list _when fetched as a Hex package_ - again, if that was fixed, then this no longer holds, and I'm fine with removing the usage of the `Mix.Dep` APIs, well, except for this next bit:

> Furthermore, if in Mix you do runtime: false and you include an app in the application list, then Mix won't remove it.

Why? That clearly deserves, at a minimum, a warning - and really it should be an error. Those are two diametrically opposed configurations: one says "start this", the other says "do not start this". Just ignoring that (or silently making a decision) isn't OK in my opinion - one of those settings is wrong and needs to be removed, and the user has to be the one to do it. I favored honoring `runtime: false`, because the subsequent check for missing applications would catch if the "removed" application was otherwise required and warn about it - going the other way means there is no warning at all, but still a potential problem.

**Comment by josevalim** [comment] 2018-08-24 22:21
> That isn't/wasn't the case though, as demonstrated in the issue here

Well, all features work as intended except when they have bugs. :) In any case, if there is a bug in Mix, then it should be reported and fixed. We have shown multiple times, including today, that we are very responsive.

But again, to be clear, the issue here is not an Elixir bug. It just happens that fixing the Hex bug also fixes this one.

> I'm fine with removing the usage of the Mix.Dep APIs, well, except for this next bit: ... Why? That clearly deserves, at a minimum, a warning - and really it should be an error. 

Sure, we can warn/error. That's not my point. My point is that you should trust the `.app` files. If you end-up reimplementing functionality then they can become inconsistent. Especially if the reimplementation of the functionality happens via private APIs.

**Comment by bitwalker** [comment] 2018-08-25 17:55
@josevalim I think we're talking past one another :) - we're in agreement that the reliance on the private API is not a good thing, nor the need to reimplement functionality. We're also in agreement that relying on the `.app` files is the best approach - none of these things are or were, being debated from my perspective.

If the plan is to warn or error about the `runtime: false`/application list conflict scenario, then there is no reason for me to try and do anything different in Distillery - it can be treated as an upstream issue or a user issue. I still anticipate issues where applications lists are manually managed, when people forgot applications, but I'll refer them here if it comes up. Those warnings will have to come from Mix.

**Comment by bitwalker** [comment] 2018-08-25 17:56
Also:

> We have shown multiple times, including today, that we are very responsive.

I hope you aren't under the impression that I'm saying you aren't - I've never said any such thing - you have always been on the ball, please don't think I'm implying otherwise.

**Closed** 2018-08-25 18:08 UTC
Labels: bug:has-workaround, deployment:packaging

**Comment by josevalim** [comment] 2018-08-25 18:14
> I hope you aren't under the impression that I'm saying you aren't - I've never said any such thing - you have always been on the ball, please don't think I'm implying otherwise.

Oh, sorry. I didn't mean to imply that you said that. :) My point is just that we should work together to improve Mix and you can count on us to fix the bugs there. Again, I'm not saying that you don't count us, I am just emphasizing it. So it seems we are in agreement all around.

> If the plan is to warn or error about the runtime: false/application list conflict scenario, then there is no reason for me to try and do anything different in Distillery

Yes, please open up an issue. :)

Thanks for removing the private API usage!

**Comment by bitwalker** [comment] 2018-08-25 18:16
>  My point is just that we should work together to improve Mix and you can count on us to fix the bugs there

Absolutely :)

> Yes, please open up an issue. :)

Will do! Probably later today though

> Thanks for removing the private API usage!

No problem, I'm always happy when I get to delete code :)
