### ISSUE TITLE
Hot Upgrade breaks when there are 2 past releases

### ISSUE THREAD

**Issue by ijunaid8989** [bitwalker/distillery#495] opened 2018-08-21 06:55 UTC
### Steps to reproduce

Distillery version 2.0
Elixir 1.7.1
OTP 21.0
First, do a normal release and deploy with `mix release`. It created a build in `prod/rel/app_name/releases/1.0.1-08f6b0c`

Application working

now change something and again create a release with mix release --upgrade

It created a new version in `prod/rel/app_name/releases/1.0.1-a4011918`

and do the upgrade as

```
/opt/app-name/bin/app-name upgrade 1.0.1-a4011918
```
Application got upgraded.

Now again make a new change create an upgrade release. version 1.0.1-a6cf7267.

now try to upgrade and it will give an error.
### Verbose ansible Logs

"Could not locate code path for release-evercam_media\",\"1.0.1-08f6b0c!"

ansible + doing manual

```
"Could not locate code path for release-evercam_media\",\"1.0.1-08f6b0c!"
```

### Description of issue

Expected: It should upgrade the new release version. but failed and finding the very first release code? is that an issue, that are 2 consecutive releases available and only should be the last one?

My config file is simple as

```
# Import all plugins from `rel/plugins`
# They can then be used by adding `plugin MyPlugin` to
# either an environment, or release definition, where
# `MyPlugin` is the name of the plugin module.
~w(rel plugins *.exs)
|> Path.join()
|> Path.wildcard()
|> Enum.map(&Code.eval_file(&1))

use Mix.Releases.Config,
    # This sets the default release built by `mix release`
    default_release: :default,
    # This sets the default environment used by `mix release`
    default_environment: Mix.env()

# For a full list of config options for both releases
# and environments, visit https://hexdocs.pm/distillery/configuration.html


# You may define one or more environments in this file,
# an environment's settings will override those of a release
# when building in that environment, this combination of release
# and environment configuration is called a profile

environment :dev do
  # If you are running Phoenix, you should make sure that
  # server: true is set and the code reloader is disabled,
  # even in dev mode.
  # It is recommended that you build with MIX_ENV=prod and pass
  # the --env flag to Distillery explicitly if you want to use
  # dev mode.
  set dev_mode: true
  set include_erts: false
  set cookie: :"Ht*Sd&uNNB]}}E;a~a/?&n~uogVhz>@|{,5`sX(>xK{A`@M,kj`0dF{s~`ry?XdJ"
end

environment :prod do
  set include_erts: true
  set include_src: false
  set cookie: :"Qf*;>$8`bG)vnRLU[AS(HLh9:]Qd:f)]%,`!Vfl^@Nek>OeeFRtl|&chJmdb{Ml("
end

# You may define one or more releases in this file.
# If you have not set a default release, or selected one
# when running `mix release`, the first release in the file
# will be used by default

release :evercam_media do
  set version: current_version(:evercam_media)
  set applications: [
    :runtime_tools
  ]
end
```

**Comment by ijunaid8989** [comment] 2018-08-21 10:59
Update:

I tried to find the first release version in build
```
root@evercam-release-test:/opt/evercam_media# grep -r "1.0.1-08f6b0c" *
Binary file bin/start_clean.boot matches
bin/evercam_media.bat:set rel_vsn=1.0.1-08f6b0c
Binary file bin/no_dot_erlang.boot matches
lib/evercam_media-1.0.1-08f6b0c/ebin/evercam_media.app:              {vsn,"1.0.1-08f6b0c"},
releases/RELEASES: {release,"evercam_media","1.0.1-08f6b0c","10.0",
releases/RELEASES:           {evercam_media,"1.0.1-08f6b0c",
releases/RELEASES:                          "./lib/evercam_media-1.0.1-08f6b0c"}],
releases/1.0.1-a2ac4195/relup: [{"1.0.1-08f6b0c",[],
releases/1.0.1-a2ac4195/relup: [{"1.0.1-08f6b0c",[],
releases/1.0.1-a2ac4195/relup:        {evercam_media,"1.0.1-08f6b0c",
releases/evercam_media.rel:{release,{"evercam_media","1.0.1-08f6b0c"},
releases/evercam_media.rel:          {evercam_media,"1.0.1-08f6b0c"}]}.
```

the very first version is still there even after an upgrade.

The problem seems to be: the release with just mix release will always stick to all version which is going to be upgraded from that.

But these all occurrences should get updated to the latest version after upgrade can you tell me where I am wrong?

**Comment by bitwalker** [comment] 2018-08-21 18:14
@ijunaid8989 Are you running the release from `_build`? The docs specifically call out the fact that you cannot run hot upgrades from there, as the upgrade operation is destructive. If you are not running them from there, and are instead deploying the tarball somewhere, can you give me the steps you follow in your deployment process? I will try to reproduce and follow up.

Additionally, it is expected that old release versions will be present after an upgrade - this is what allows the system to revert to an older version (i.e. downgrade). There is metadata in various files which tracks which release is active/installed/made permanent.

**Comment by ijunaid8989** [comment] 2018-08-22 03:12
@bitwalker Thanks for your reply.

First I will tell all the steps for a fresh deploy with distillery.

These are ansible steps I performed whie a fresh deploy.

build_dir is /tmp/build-media
remote_media_dir is /opt/evercam_media

It simply doing:

1. Fetching local commit
2. Deleting build directory if present
3. clone, mix, compile with ENV vars
4. doing mix release
5. Registering release version `cat {{build_dir}}/_build/prod/rel/evercam_media/releases/start_erl.data | awk '{print $2}`
6. Extracting/unziping the newly created release to remote directory (/opt/evercam_media/)`{{build_dir}}/_build/prod/rel/evercam_media/releases/{{evercam_media_version.stdout}}/evercam_media.tar.gz`
7. Then we do a start and stop to the service we have created. and It starts from remote directory not build directory

<summary>
  <details>
- name: Register evercam-media local commit hash
  local_action:
    shell
    chdir={{local_media_dir}}
    git rev-parse --short HEAD
  register: local_commit_hash

- name: Delete build directory
  file:
    path: "{{build_dir}}"
    state: absent

- name: Clone evercam-media
  git:
    repo: https://github.com/evercam/evercam-media
    dest: "{{build_dir}}/"
    version: "{{local_commit_hash.stdout}}"

- name: Get evercam-media dependencies
  shell: "bash -lc '{{mix_env_vars}} {{media_env_vars}} mix deps.get'"
  args:
    chdir: "{{build_dir}}"

- name: Compile evercam-media application
  shell: "bash -lc '{{mix_env_vars}} {{media_env_vars}} mix compile'"
  args:
    chdir: "{{build_dir}}"
  failed_when: False

- name: Compile again so any flaky dependencies are recompiled
  shell: "bash -lc '{{mix_env_vars}} {{media_env_vars}} mix compile'"
  args:
    chdir: "{{build_dir}}"

- name: Build evercam-media application release
  shell: "bash -lc '{{mix_env_vars}} {{media_env_vars}} mix release'"
  args:
    chdir: "{{build_dir}}"

- name: Register the version of the release
  shell: "cat {{build_dir}}/_build/prod/rel/evercam_media/releases/start_erl.data | awk '{print $2}'"
  register: evercam_media_version

- name: Ensure there is a directory for the application
  file: path="{{remote_media_dir}}" state=directory

- name: Copy the release to the application directory
  unarchive:
    copy: no
    src: "{{build_dir}}/_build/prod/rel/evercam_media/releases/{{evercam_media_version.stdout}}/evercam_media.tar.gz"
    dest: "{{remote_media_dir}}"
  </details>
</summary>


After that I do hot code deploy (new changes).

Details about this.

1. Fetching local commit.
2. check for old `_build` folder.
3. If its there then move it to another location.
4. Deleted build directory.
5. clone repo, move old build folder again to `/tmp/build-media/_build`.
6. create apppup file, `"bash -lc '{{mix_env_vars}} {{media_env_vars}} mix release.gen.appup --app=evercam_media'"` (I have tried with and without this as well)
7. mix, compile, with ENV vars `mix release --upgrade`.
8. Get new release version from `start_erl.data`.
9. Copy this time NO Extraction but copy the release folder for  example in past there were folders like in release directory.

```
1.0.1-a2ac4195	1.0.1-a8a5f923	RELEASES  start_erl.data
```
lets say `1.0.1-a8a5f923` this is new one. I just copied this whole folder to 
```
root@evercam-release-test:~# cd /opt/evercam_media/
root@evercam-release-test:/opt/evercam_media# ls
bin  erts-10.0	lib  releases  var
root@evercam-release-test:/opt/evercam_media# cd releases/
root@evercam-release-test:/opt/evercam_media/releases#
```
releases where is the remote directory.

then I did an upgrade as `/opt/evercam_media/bin/evercam_media upgrade 1.0.1-a8a5f923`

It worked new application released fine but 

If repeat the 2nd whole process again with a new release it gave me the error as

```
"Could not locate code path for release-evercam_media\",\"1.0.1-a2ac4195!"
```

Instead of looking for 2nd last one. the 3rd release always looks for first one. also as I have posed the signs of first replease values still there in /opt/evercam_media and /tmp/build-media.

<summary>
  <details>
- name: Register evercam-media local commit hash
  local_action:
    shell
    chdir={{local_media_dir}}
    git rev-parse --short HEAD
  register: local_commit_hash

- name: List files in build directory
  command: "ls {{build_dir}}/_build"
  register: dir_out

- name: Stat build directory
  stat: path={{build_dir}}/_build
  register: _build

- name: Stat if any old build present
  stat: path=/tmp/_old_build
  register: _old_build

- name: Move _build to new place
  command: mv {{build_dir}}/_build /tmp/_old_build
  when: _old_build.stat.exists == False

- name: Delete build directory
  file:
    path: "{{build_dir}}"
    state: absent

- name: Clone evercam-media
  git:
    repo: https://github.com/evercam/evercam-media
    dest: "{{build_dir}}/"
    version: "{{local_commit_hash.stdout}}"

- name: Move old build to new clone.
  command: mv /tmp/_old_build {{build_dir}}/_build

- name: Get evercam-media dependencies
  shell: "bash -lc '{{mix_env_vars}} {{media_env_vars}} mix deps.get'"
  args:
    chdir: "{{build_dir}}"

- name: Compile evercam-media application
  shell: "bash -lc '{{mix_env_vars}} {{media_env_vars}} mix compile'"
  args:
    chdir: "{{build_dir}}"
  failed_when: False

- name: Compile again so any flaky dependencies are recompiled
  shell: "bash -lc '{{mix_env_vars}} {{media_env_vars}} mix compile'"
  args:
    chdir: "{{build_dir}}"

- name: Create an appup file
  shell: "bash -lc '{{mix_env_vars}} {{media_env_vars}} mix release.gen.appup --app=evercam_media'"
  args:
    chdir: "{{build_dir}}"

- name: Build evercam-media application release
  shell: "bash -lc '{{mix_env_vars}} {{media_env_vars}} mix release --upgrade'"
  args:
    chdir: "{{build_dir}}"

- name: Register the version of the release
  shell: "cat {{build_dir}}/_build/prod/rel/evercam_media/releases/start_erl.data | awk '{print $2}'"
  register: evercam_media_version

- name: Ensure there is a directory for the application
  file: path="{{remote_media_dir}}" state=directory

- name: Copy new release to {{remote_media_dir}}
  command: cp -r {{build_dir}}/_build/prod/rel/evercam_media/releases/{{evercam_media_version.stdout}} {{remote_media_dir}}/releases/{{evercam_media_version.stdout}}

- name: Upgrade to new version
  command: "{{remote_media_dir}}/bin/evercam_media upgrade {{evercam_media_version.stdout}}"

- name: Display post upgrade message
  debug:
    msg:
      - 'Evercam Server release has been upgraded.'
      - '- New Version: {{evercam_media_version.stdout}}'

  </details>
</summary>

I am sure that I am wrong at somewhere so please guide me, I really looking forward to use this feature.

PS: I also tried Edeliver and Distillery together yesterday , Edeliver seems **never** to work.

**Comment by bitwalker** [comment] 2018-08-22 22:36
This is fixed in master, I should have a new release out soon

**Closed** 2018-08-22 22:36 UTC

**Comment by ijunaid8989** [comment] 2018-08-23 05:28
Okay, @bitwalker Thanks for your reply.

I have a question that in documentation its written to create an appup before doing `--upgrade`. When I don't create the appup myself. --upgrade create it by itself. Should I skip that step or not?

Also talking about hot upgrades, We have so many camera workers running at a time, I haven't reached that point so far to test it by myself but we new hot upgrade happens it also give a reload to all running processes?

**Comment by ijunaid8989** [comment] 2018-08-27 07:00
After updating the version to the latest release.

The whole process is the same. first hot upgrade worked and on the 2nd one. I got this error.

```
root@evercam-release-test:~# /opt/evercam_media/bin/evercam_media upgrade 1.0.1-a42e5917
▸  Received 'pang' from evercam_media@127.0.0.1!
▸  Possible reasons for this include:
▸    - The cookie is mismatched between us and the target node
▸    - We cannot establish a remote connection to the node
Node evercam_media@127.0.0.1 is not running!
```

```
root@evercam-release-test:~# /opt/evercam_media/bin/evercam_media ping
▸  Received 'pang' from evercam_media@127.0.0.1!
▸  Possible reasons for this include:
▸    - The cookie is mismatched between us and the target node
▸    - We cannot establish a remote connection to the node
root@evercam-release-test:~# /opt/evercam_media/bin/evercam_media remote_console
▸  Received 'pang' from evercam_media@127.0.0.1!
▸  Possible reasons for this include:
▸    - The cookie is mismatched between us and the target node
▸    - We cannot establish a remote connection to the node
Node evercam_media@127.0.0.1 is not running!
root@evercam-release-test:~#
```
Though the server is running (http://95.216.167.191:4000/v1/users/junaid@evercam.io?api_id=dfba63c8&api_key=53dbfa7bb3a64e9a9e170bf3d02e2d1a)

can you please guide what is the issue now?

**Comment by ijunaid8989** [comment] 2018-08-27 09:35
@pierot this one https://github.com/bitwalker/distillery/issues/495#issuecomment-416133600 or this one https://github.com/bitwalker/distillery/issues/495#issuecomment-416138504 ?

**Comment by pierot** [comment] 2018-08-27 09:41
This one: https://github.com/bitwalker/distillery/issues/495#issuecomment-416133600

**Comment by ijunaid8989** [comment] 2018-08-27 09:43
@pierot Thanks for the confirmation. 

I am having many issues at the moment with the hot upgrade, was that worked for you in past?

**Comment by pierot** [comment] 2018-08-27 10:52
Hot upgrades have worked almost all the time. If there were issues this fix was mostly stopping and restarting the application or building and deploying a full release.

**Comment by ijunaid8989** [comment] 2018-08-27 11:38
How were you doing that? In my case, if you read the full thread. I always had an issue when I am doing 3rd hot code deploy. can you share how you were doing hot code upgrades with an Elixir project?

**Comment by ijunaid8989** [comment] 2018-08-28 06:55
Thanks for considering it again.

Okay as you labelled it can't reproduce. The process is very same. as I mentioned above. and I just updated to 2.0.8 version. after that, as first I was getting an error on 2nd upgrade. Now I am getting the error at same but the error is different and also @pierot getting the same error.

**Comment by ijunaid8989** [comment] 2018-08-28 07:34
Just for more information:

I used github master branch in mix.ex and deployed. 

The first scratch deploy. It worked fine. (v1.0.1-a772f001 )
```
root@evercam-release-test:/opt/evercam_media/releases# ls
1.0.1-a772f001 RELEASES  evercam_media.rel  start_erl.data
```

2nd hot code upgrade. worked fine. (v1.0.1-a23218f9)

```
root@evercam-release-test:/opt/evercam_media/releases# ls
1.0.1-a23218f9	1.0.1-a772f001 RELEASES  evercam_media.rel  start_erl.data
```

3rd hot code upgrade gave an error as (v1.0.1-ad75b35d)
```
root@evercam-release-test:/opt/evercam_media/releases# ls
1.0.1-a23218f9	1.0.1-a772f001	1.0.1-ad75b35d	RELEASES  evercam_media.rel  start_erl.data
```

```
▸  Release handler check for evercam_media:1.0.1-ad75b35d failed with: {:no_matching_relup, '1.0.1-ad75b35d', '1.0.1-a23218f9'}
```

**Comment by ijunaid8989** [comment] 2018-08-28 08:32
For follow up. I found something here. https://github.com/edeliver/edeliver/issues/123#issuecomment-233086187
It's about auto-versioning of application that can be an issue here? 

```
  def project do
    {result, _exit_code} = System.cmd("git", ["rev-parse", "HEAD"])
    git_sha = String.slice(result, 0, 7)

    [app: :evercam_media,
     version: "1.0.1-a#{git_sha}",
     elixir: "~> 1.7",
     elixirc_paths: elixirc_paths(Mix.env),
     build_embedded: Mix.env == :prod,
     start_permanent: Mix.env == :prod,
     compilers: [:phoenix] ++ Mix.compilers,
     aliases: aliases(),
     deps: deps()]
  end
```

we are doing it this way?

**Comment by bitwalker** [comment] 2018-08-28 16:58
@ijunaid8989 The error is saying that there is no relup describing how to upgrade from `1.0.1-a23218f9` to `1.0.1-ad75b35d`. The first thing I would check for the relup file, which should be at `_build/<env>/rel/<app>/releases/1.0.1-ad75b35d/relup`. Open this in a text editor, and you will see something like the following:

```erlang
{"0.2.0",
 [{"0.1.0",[],
   [{load_object_code,{test,"0.2.0",['Elixir.TestWeb.Gettext']}},
    point_of_no_return,
    {load,{'Elixir.TestWeb.Gettext',brutal_purge,brutal_purge}}]}],
 [{"0.1.0",[],
   [{load_object_code,{test,"0.1.0",['Elixir.TestWeb.Gettext']}},
    point_of_no_return,
    {load,{'Elixir.TestWeb.Gettext',brutal_purge,brutal_purge}}]}]}.
```

This tuple is basically of the form `{target_version, [{source_version, _, upgrade instructions}], [{source_version, _, downgrade_instructions}]}`. When the release handler tries to apply an upgrade, it is going to look for this file, and it is going to look for matching source and target versions, where the source must match the current version of the release, and the target much match the version you are trying to upgrade to. If there is no match, then the upgrade cannot proceed, because the release handler has no instructions.

So to figure out why it's saying it cannot find a matching `relup`, we have to figure out what is actually _in_ the relup of the newest version you are trying to upgrade to. The best place to check is in the `_build/<env>/rel/<app>/releases/<target version>/relup` file, since it is the same as the one the release handler checks.

**Comment by bitwalker** [comment] 2018-08-28 17:05
> Okay as you labelled it can't reproduce. The process is very same. as I mentioned above. and I just updated to 2.0.8 version. after that, as first I was getting an error on 2nd upgrade. Now I am getting the error at same but the error is different and also @pierot getting the same error.

I labelled it "cannot reproduce" because I cannot reproduce it - the steps you provide me do not result in any error. I can hot upgrade a Phoenix project several times in a row with no issue. This means the problem is something specific to your project, build environment, or the interaction with edeliver. I'm reopening this issue so that we can figure out which of those it is, but I do not believe there is a bug in Distillery at this point, at least as described.

**Comment by ijunaid8989** [comment] 2018-08-28 18:04
Okay, I will get back with more information. I am not using Edeliver now it was just a test when I used it right now its just distillery.

**Comment by ijunaid8989** [comment] 2018-08-29 06:09
@bitwalker thank you everything is working fine. 

I am having an issue with versions of the app. In the past as I mentioned I was doing it with.

```
{result, _exit_code} = System.cmd("git", ["rev-parse", "HEAD"])
git_sha = String.slice(result, 0, 7)
```

But when I did with hand just `1.01` , `1.0.2`, `1.0.3` and it worked well. But can you guide the best way to do the auto-versioning?
