### ISSUE TITLE
Loading of system NIFs is failing with include_erts false

### ISSUE THREAD

**Issue by bjuretic** [bitwalker/distillery#436] opened 2018-07-28 19:01 UTC
With the latest master I create a release on Elixir 1.7.1 (erts-10.0.3) and `set include_erts: false` in config.exs . The code is compiled and release created in the similar Alpine container (it just has build tools installed as opposed to the runtime container), so it is not about differences in ERTS version.

```
$ docker run -it --entrypoint /bin/bash -p 4001:4001 myapp/auth:latest
bash-4.4# bin/auth console
Erlang/OTP 21 [erts-10.0.3] [source] [64-bit] [smp:6:6] [ds:6:6:10] [async-threads:1] [hipe]

2018-07-28 18:55:59.263629
    args: [load_failed,"Failed to load NIF library: 'Error loading shared library /opt/app/lib/asn1-5.0.6/priv/lib/asn1rt_nif.so: No such file or directory'"]
    format: "Unable to load asn1 nif library. Failed with error:~n\"~p, ~s\"~n" 
```

It is looking for .so libraries in the wrong place - in the home of the release (for the app) and not in the system location for ERTS libs:

```
# ls /usr/lib/erlang/lib/asn1-5.0.6/priv/lib/asn1rt_nif.so
/usr/lib/erlang/lib/asn1-5.0.6/priv/lib/asn1rt_nif.so
```

I've seen this bug in some old issue, but it seems to be back in the latest code.

p.s. In bitwalker/alpine-elixir:1.7.1  - "grep" needs to be installed or the erts.sh blows up when starting an application. It complains about invalid regular expressions, while in fact just the grep which comes by default does not support them. So adding `apk add --update grep` in my Dockerfile fixed that part.

**Comment by bitwalker** [comment] 2018-07-30 16:33
I think the problem is that `include_system_libs` is set to true, I've fixed the loophole for that locally, so once that gets pushed to master I think you'll be in good shape - I'll keep this open until you confirm though.

Thanks for the tip about grep missing, I'll make sure it is added to my Alpine image.

**Comment by bitwalker** [comment] 2018-07-31 02:38
I've pushed my set of changes locally, can you confirm the fix on your end?

**Comment by 4eek** [comment] 2018-07-31 06:09
Regarding `grep` above... Extended Mode uses { and } as special characters. Making grep
implementations other then GNU grep fail (see
http://www.gnu.org/software/grep/manual/grep.html#Basic-vs-Extended).

You could use `-e` instead of `-E` if Extended Mode is not needed for that grep.

I have tested it successfully my side and it works fine. Do you want a PR?

**Comment by bitwalker** [comment] 2018-07-31 07:07
@4eek I'd accept a PR, sure, I'll need to do some further testing to make sure it works, as I believe I chose extended mode for a reason, but perhaps that was somewhere else and I just followed suit here.

**Comment by bjuretic** [comment] 2018-07-31 08:02
@bitwalker No luck, with `set include_erts: false ` it still looks for it in $release/lib:

```
$ bin/auth console
Erlang/OTP 21 [erts-10.0.3] [source] [64-bit] [smp:6:6] [ds:6:6:10] [async-threads:1] [hipe]

2018-07-31 07:53:21.420027
    args: [load_failed,"Failed to load NIF library: 'Error loading shared library /opt/app/lib/asn1-5.0.6/priv/lib/asn1rt_nif.so: No such file or directory'"]
    format: "Unable to load asn1 nif library. Failed with error:~n\"~p, ~s\"~n"
    label: {error_logger,error_msg}
```

**Comment by 4eek** [comment] 2018-07-31 08:04
@bitwalker more testing showed that `-e` does not work as expected and is not a valid solution. However, encapsulating `{` into `[{]` so it is not interpreted as 'grouping' does work so far. I will submit PR to move discussion there rather.

**Comment by bitwalker** [comment] 2018-08-02 16:56
Fixed in master

**Closed by bitwalker** 2018-08-02 16:56 UTC
Labels: 2.0

**Comment by bjuretic** [comment] 2018-08-02 19:06
@bitwalker Sorry repo is too complex. It works on my osx and does not work in Alpine container (your alpine-elixir), so let's just say it is fixed and if I later discover the issue in the container I will let you know.

**Comment by bitwalker** [comment] 2018-08-02 19:10
As soon as I get a chance I'll try and repro in an Alpine image, but it should be fixed now (another user had the same issue and I was able to track it down with their sample app). It may be something else though, so I'll try to take a look.

**Comment by bjuretic** [comment] 2018-08-02 19:46
No need - it works, I just checked again. I did not explicitly tell mix to use a `tag` with the latest release from github so it seems it was using the old code for some reason. Works fine now (on your alpine-linux container as well). Thanks for the fine help. :)
