### ISSUE TITLE
Error in sys.config: configuration file must contain ONE list ended by <dot>

### ISSUE THREAD

**Issue by lessless** [bitwalker/distillery#197] opened 2017-02-01 16:30 UTC
### Steps to reproduce

- Create an umbrella app with two child applications: phoenix  app and supervised mix app
- Setup distillery 
- Setup deliver

Each second deploy will fail (I wish I would know how to reproduce, actually)
### Verbose Logs

`mix edeliver update staging --start-deploy --branch=master --verbose`

https://gist.github.com/lessless/8b73d75cd84660b8a7e58e6230f7b8f6

### Description of issue

Each second deploy fails with 
```
{"could not start kernel pid",application_controller,"error in config file \"/var/www/app_name/var/sys.config\" (none): configuration file must contain ONE list ended by <dot>"}
could not start kernel pid (application_controller) (error in config file "/var/www/app_name/var/sys.config" (none): configuration file must contain ONE list ended by <dot>)
```
while  sys.config contains exactly one list and has dot at the end 

https://gist.github.com/lessless/499d281c0cf0eb9edde40d159880cde3

- What are the expected results?
New version is successfully started 

- What OS, Erlang/Elixir versions are you seeing this issue on?

  - Ubuntu 16.04
  - Erlang/OTP 19 [erts-8.2] [source] [64-bit] [smp:2:2] [async-threads:10] [kernel-poll:false]
  - Elixir 1.4.0

- If possible, also provide your `rel/config.exs`, as it is often
  my first troubleshooting question, and you'll save us both time :)
```
use Mix.Releases.Config,
    default_release: :app_name,
    default_environment: :prod

environment :dev do
  set dev_mode: true
  set include_erts: false
  set cookie: :"...."
end

environment :prod do
  set include_erts: true
  set include_src: false
  set cookie: :"...."
end

release :app_name do
  set version: current_version(:app_name)
  set applications: [
    app_name: :permanent,
    postman: :permanent
  ]
end
```
- Is there documentation that says one thing, but Distillery does
  another? If so, please link the doc here so it can be updated if
  it's a documentation issue, or so that the fix can be based around
  what's documented.

No

**Comment by dbulic** [comment] 2017-02-01 21:25
I believe this is related: https://elixirforum.com/t/edeliver-wont-start-project-at-production/2818/8

**Comment by bitwalker** [comment] 2017-02-02 02:08
Can you isolate this issue to just distillery? I'm unfamiliar with edeliver's inner workings, and Distillery shouldn't ever produce invalid `sys.config` files, so I'm skeptical that this is a problem caused by Distillery and not by edeliver - that said, if you can provide me a reproducible case without edeliver, I'll be glad to dig in.

**Comment by lessless** [comment] 2017-02-02 04:19
Hello Paul,

according to the link above it's an edeliver issue

**Comment by dbulic** [comment] 2017-02-02 06:37
@lessless, can you post that to edeliver's issue list?

**Comment by bitwalker** [comment] 2017-02-03 03:56
I'll close this for now then, feel free to reopen if there is an issue with Distillery though!

**Closed by bitwalker** 2017-02-03 03:56 UTC
Labels: cannot reproduce

**Comment by David-Gil** [comment] 2019-05-15 13:21
In my case, everything was going ok until I updated Distillery from 1.5.5 to 2.0.13. Now I can only run the app once because the second time it says:

```shell
could not start kernel pid (application_controller) (error in config file "/home/vagrant/app/_build/prod/rel/app/var/sys.config" (none): no ending <dot> found)

Crash dump is being written to: erl_crash.dump...done
{"could not start kernel pid",application_controller,"error in config file \"/home/vagrant/app/_build/prod/rel/app/var/sys.config\" (none): no ending <dot> found"}
Unable to configure release!
```

I had edeliver in mix.exs but wasn't using it, so I removed it completely.
I don't have any env var with json either, AFAICS.

* What OS, Erlang/Elixir versions are you seeing this issue on?

   - Ubuntu 16.04 (Vagrant environment)
   - Erlang/OTP 21 [erts-10.2] [source] [64-bit] [smp:2:2] [ds:2:2:10] [async-threads:1] [hipe]
   - Elixir 1.8.1

If possible, also provide your rel/config.exs, as it is often
my first troubleshooting question, and you'll save us both time :)

```elixir
# Import all plugins from `rel/plugins`
# They can then be used by adding `plugin MyPlugin` to
# either an environment, or release definition, where
# `MyPlugin` is the name of the plugin module.
~w(rel plugins *.exs)
|> Path.join()
|> Path.wildcard()
|> Enum.map(&Code.eval_file(&1))

use Mix.Releases.Config,
    # This sets the default release built by `mix release`
    default_release: :default,
    # This sets the default environment used by `mix release`
    default_environment: Mix.env()

# For a full list of config options for both releases
# and environments, visit https://hexdocs.pm/distillery/config/distillery.html


# You may define one or more environments in this file,
# an environment's settings will override those of a release
# when building in that environment, this combination of release
# and environment configuration is called a profile

environment :dev do
  # If you are running Phoenix, you should make sure that
  # server: true is set and the code reloader is disabled,
  # even in dev mode.
  # It is recommended that you build with MIX_ENV=prod and pass
  # the --env flag to Distillery explicitly if you want to use
  # dev mode.
  set dev_mode: true
  set include_erts: false
  set cookie: :"......."
end

environment :prod do
  set include_erts: true
  set include_src: false
  set cookie: :"......"
end

# You may define one or more releases in this file.
# If you have not set a default release, or selected one
# when running `mix release`, the first release in the file
# will be used by default

release :app do
  set version: current_version(:app)
  set applications: [
    :runtime_tools
  ]
end
```
