### ISSUE TITLE
start_erl.data overwritten on stop of app

### ISSUE THREAD

**Issue by Hermanverschooten** [bitwalker/distillery#217] opened 2017-03-08 19:16 UTC
I upgraded distillery from version 1.1.0 to 1.2.2.
I am using exrm_deb to create a deb file for my project.

Up until now everything was working fine, exrm_deb unpacks the release to its release/version folder and start_erl.data is pointed to this release. Normally restarting your app is sufficient to get the new release.  But since the upgrade to 1.2.2, start_erl.data is overwritten with the release that was just stopped. So my normal procedure of issuing `bin/appname restart` no longer works, as the old version is restarted.

**Comment by bitwalker** [comment] 2017-03-08 19:24
Hm, `start_erl.data` is generated by the assembler, it sounds to me like `start_erl.data` is not being copied into the `.deb`. Can you put together a little repro project that I can clone and test with?

**Comment by Hermanverschooten** [comment] 2017-03-08 19:29
It is copied into the deb, because when I install my deb it is there. It is only when I stop the current running version it is overwritten.

**Comment by bitwalker** [comment] 2017-03-08 19:34
That's because `start_erl.data` is written to by the boot script. It seems to me the correct installation procedure should stop the running program before updating it if not using hot upgrades. I don't know if it will be possible to avoid writing `start_erl.data` from the boot script, but I can look into it.

**Comment by Hermanverschooten** [comment] 2017-03-08 19:36
It didn't do this before.  I cannot stop the program to perform the update as it is running remotely, and is servicing customers. I do want to use hot upgrades, but ran into issues when there is a new version of elixir, it has no appup.

**Comment by Hermanverschooten** [comment] 2017-03-08 20:00
The difference is in the script.
In the old version it did
```
# If ERTS_VSN is not set, detect it
if [ -z "$ERTS_VSN" ]; then
    ERTS_VSN="$(_detect_erts_vsn)"
    echo "$ERTS_VSN $REL_VSN" > "$START_ERL_DATA"
fi
```

While in the new version it just does:

```
# Make sure ERTS configuration is set
_init_erts_config
echo "$ERTS_VSN $REL_VSN" > "$START_ERL_DATA"
```

So it is overwritten on any command you execute.

**Comment by bitwalker** [comment] 2017-03-08 20:01
`start_erl.data` is being written now to fix a bug when ERTS is not included, so while it didn't do it before, it doesn't mean it was not supposed to. Performing updates in this way was not something I anticipated - hot upgrades handle updating `start_erl.data` automatically, but unpacking a new release package over the top of the last while it's still running is something which is difficult to ensure works perfectly.

I'm also confused here, you say you can't stop the application to update, but that's exactly what you are already doing when you call `restart`. The time spent unpacking the release *after* stopping is so small that it's not worthy of concern - if you can stop the application at all, you can stop it in the order needed to apply the update in the correct order.

I'll look into improving this so that perhaps it will work for your case again, but I have to say this is a use case I'm not particularly keen on officially supporting - it's error-prone to say the least.

**Comment by Hermanverschooten** [comment] 2017-03-08 20:16
I understand your concern, but can you then explain the use of the install command? It says install the version, but not upgrade to it. I tried this now, and it tells me
```
# bin/gwserver install 2.1.1
Release 2.1.1 is already unpacked
Release 2.1.1 is already installed, and set permanent.
```
But I cannot start this release, as release/start_erl.data is set to 2.0.7.

The other issue is probably with exrm_deb, it does not contain the tar.gz file.

What would be the procedure to do the upgrade?

1. stop the current version
2. ?
3. start again

I tried `bin/gwserver install 2.1.1` with the app stopped, but that doesn't work `Node is not running!`

My problem is not restarting the app, but I am sending a command to the app to update itself using `apt`;
```
System.cmd "apt", ["update"]
System.cmd "apt", ["-y", "upgrade", "gwserver"]
System.cmd "service", ["gwserver", "restart"]
```

**Comment by bitwalker** [comment] 2017-03-08 20:25
`install` does not modify `start_erl.data`, it simply prepares the target system to be updated by unpacking files, etc. It has to be upgraded in order for the new version to take effect.

Procedure to update is simply `bin/myapp stop && install_deb && bin/myapp start`. I'm not familiar with how exrm_deb is implementing the upgrade handler for the package, I would expect that it should provide a way to hook into the event and execute a shell script, if not, I would definitely push for that because it would simplify this a great deal by allowing you just tell `apt` to update the program and then be done with it.

If that's not viable for some reason, is there a reason why doing the update via `ssh` is not possible? It would make it trivial to automate this.

**Comment by Hermanverschooten** [comment] 2017-03-08 20:36
Doing this by ssh is not possible, because the app is a Hotspot Gateway, that will be running on several 100 machines in the near future. At the moment I am running this on a small subset, about 25 machines that are located throughout Belgium. Most machines are not accessible by ssh, as they run behind NAT routers.

I could create an update script that is started separately from the app, but since I am including ERTS in the release, the installation is ~287Mb, the internet quality would then decide how long the app is offline.  In the mean time people would either not get on the internet, or would have unregistered access, neither option is viable.

**Comment by Hermanverschooten** [comment] 2017-03-08 20:54
Looking at the code in the boot file, in _init_erts_config(), you first check to see if $ERTS_VSN is set, and if it is, if the folder exist, if not you unset ERTS_VSN and try again.  If $ERST_VSN is not set, you try to find the system erl and error out if that is not found.  Couldn't we move the rewriting of start_erl.data to the section following that if-block? It is where you set ERTS_VSN to the version found. So in my case it will never get there as I include ERTS. And if ERTS is not included, but available it gets rewritten.

**Comment by bitwalker** [comment] 2017-03-08 21:03
I've pushed that change to master, but it leaves the edge case of not including ERTS unhandled.

I was not suggesting stopping the app while you download the update, only when it's being applied. This *should* be able to be done by implementing an update callback for the packaging system (.deb) in this case, but perhaps .deb packages don't offer such capability. If it does, my suggestion is to stop before the update is applied there, and start after it's applied, via `pre/post` hooks, if such things are available.

In any case, since this is fixed in master for your use case, I suspect there isn't much point for you to change the way you are doing it today, but I would definitely suggest looking into changing it up, because if there is ever a reason why I can't support that use case, you may be left in a tight spot.

**Comment by Hermanverschooten** [comment] 2017-03-08 21:08
You are my hero!  And I will definitely look into those hooks.

But I do not see the edge case, unless you mean having a different ERTS version in start_erl.data than the one specified in ERTS_VSN.

**Comment by bitwalker** [comment] 2017-03-08 21:10
If ERTS is not included, then it will continue to overwrite `start_erl.data`, so someone doing the same thing you are, but not including ERTS will have the same problem, but with no fix possible.

**Comment by Hermanverschooten** [comment] 2017-03-08 21:12
The only fix then would be to look at start_erl.data and only replace the ERTS part, leaving the version untouched.

**Comment by bitwalker** [comment] 2017-03-08 21:16
Actually that's exactly what we're doing, the boot loader script sets `REL_VSN` by reading `start_erl.data`.

**Comment by Hermanverschooten** [comment] 2017-03-08 21:17
something like 
```
CURRENT_REL = $(cat "$START_ERL_DATA" | cut -d' ' -f2)
echo "$ERTS_VSN $CURRENT_REL" > "$START_ERL_DATA"
```

**Comment by bitwalker** [comment] 2017-03-08 21:20
That's exactly what happens when you run `bin/myapp <task>`, it sets `$REL_VSN` by parsing `start_erl.data`

**Comment by Hermanverschooten** [comment] 2017-03-08 21:22
Yeah, I saw that, that's were I got the idea.
Maybe even better to do it like this
```
echo "$ERTS_VSN ${$CURRENT_REL:-$REL_VSN}" > "$START_ERL_DATA"
```
So that if there is no current releases in start_erl.data it takes the current one.

**Comment by Hermanverschooten** [comment] 2017-03-08 21:25
If we put this in a separate update_erl_start function, it could go back to its original place in the flow.

**Comment by bitwalker** [comment] 2017-03-08 21:27
There will always be a release in `start_erl.data`, so that's already handled. The problem in your case is that you are using `restart`, which does not restart the emulator, so `start_erl.data` is not used. You would need to use `reboot` with heart enabled, or issue `stop` and `start` commands as we discussed.

**Comment by bitwalker** [comment] 2017-03-08 21:30
Basically, what I'm saying is that the current behaviour is working as intended, and correctly - this specific edge case is best handled using other means, but it currently works with the fix I pushed, just be aware that it's not future-proof.

**Comment by Hermanverschooten** [comment] 2017-03-08 21:30
Aha, but I am doing a stop/start cycle, as this is what's in the init-script.

**Comment by bitwalker** [comment] 2017-03-08 21:31
I thought you said you were using the `restart` task?

**Comment by Hermanverschooten** [comment] 2017-03-08 21:32
No, I do a `service gwserver restart`, with does a stop/start.

**Comment by Hermanverschooten** [comment] 2017-03-08 21:33
OK, I see, I erroneously put that in my opening comment, as I was doing it manually at that time. But in the program I am using the service that does a stop/start. Sorry about the confusion.

**Comment by bitwalker** [comment] 2017-03-08 21:34
If `start_erl.data` is being updated prior to the `stop` or the `start`, then it should have the correct version, unless the release is being unpacked incorrectly. `$REL_VSN` will only ever have what's in `start_erl.data`, so if that was set to the wrong thing, then `start_erl.data` was never actually updated.

**Comment by bitwalker** [comment] 2017-03-08 21:36
The only exception I can see to that would be if a hook unset `REL_VSN` and set it to something else, otherwise it's just not possible for the boot script to have reverted the value, the value it gets is always the value at the time the boot script is executed.

**Comment by Hermanverschooten** [comment] 2017-03-08 21:49
![out](https://cloud.githubusercontent.com/assets/91784/23725536/4c6d07ba-0451-11e7-9544-3a39ed2f5e11.gif)

**Comment by bitwalker** [comment] 2017-03-08 21:51
Could you repeat that but with `DEBUG_BOOT=true`? Just paste the output here in a code block.

**Comment by Hermanverschooten** [comment] 2017-03-08 21:54
```
root@GratWiFi:/opt/gwserver# DEBUG_BOOT=true bin/gwserver stop
+ uname
+ grep -q Darwin
+ readlink -f /opt/gwserver/releases/2.1.1/gwserver.sh
+ SCRIPT=/opt/gwserver/releases/2.1.1/gwserver.sh
+ dirname /opt/gwserver/releases/2.1.1/gwserver.sh
+ SCRIPT_DIR=/opt/gwserver/releases/2.1.1
+ dirname /opt/gwserver/releases/2.1.1
+ dirname /opt/gwserver/releases
+ RELEASE_ROOT_DIR=/opt/gwserver
+ RUN_ERL_DISABLE_FLOWCNTRL=true
+ REL_NAME=gwserver
+ REL_VSN=2.1.1
+ ERTS_VSN=8.2
+ CODE_LOADING_MODE=embedded
+ START_ERL_DATA=/opt/gwserver/releases/start_erl.data
+ REL_DIR=/opt/gwserver/releases/2.1.1
+ REL_LIB_DIR=/opt/gwserver/lib
+ ERL_OPTS=
+ RELEASE_MUTABLE_DIR=/opt/gwserver/var
+ RUNNER_LOG_DIR=/opt/gwserver/var/log
+ EXTRA_OPTS=
+ PRE_CONFIGURE_HOOKS=/opt/gwserver/releases/2.1.1/hooks/pre_configure.d
+ PRE_START_HOOKS=/opt/gwserver/releases/2.1.1/hooks/pre_start.d
+ POST_START_HOOKS=/opt/gwserver/releases/2.1.1/hooks/post_start.d
+ PRE_STOP_HOOKS=/opt/gwserver/releases/2.1.1/hooks/pre_stop.d
+ POST_STOP_HOOKS=/opt/gwserver/releases/2.1.1/hooks/post_stop.d
+ PRE_UPGRADE_HOOKS=/opt/gwserver/releases/2.1.1/hooks/pre_upgrade.d
+ POST_UPGRADE_HOOKS=/opt/gwserver/releases/2.1.1/hooks/post_upgrade.d
+ [ -z xterm-256color ]
+ _init_erts_config
+ [ -z 8.2 ]
+ __erts_dir=/opt/gwserver/erts-8.2
+ [ -d /opt/gwserver/erts-8.2 ]
+ export ROOTDIR=/opt/gwserver
+ export ERTS_DIR=/opt/gwserver/erts-8.2
+ echo 8.2 2.1.1
+ [ -z  ]
+ export RELEASE_CONFIG_DIR=/opt/gwserver
+ mkdir -p /opt/gwserver/var
+ echo Files in this directory are regenerated frequently, edits will be lost
+ mkdir -p /opt/gwserver/var/log
+ _init_configs
+ [ -z  ]
+ [ -f /opt/gwserver/vm.args ]
+ export VMARGS_PATH=/opt/gwserver/releases/2.1.1/vm.args
+ export SRC_VMARGS_PATH=/opt/gwserver/releases/2.1.1/vm.args
+ [ /opt/gwserver/releases/2.1.1/vm.args != /opt/gwserver/var/vm.args ]
+ echo #### Generated - edit/create /opt/gwserver/vm.args instead.
+ cat /opt/gwserver/releases/2.1.1/vm.args
+ export VMARGS_PATH=/opt/gwserver/var/vm.args
+ [ ]
+ [ -z  ]
+ [ -f /opt/gwserver/sys.config ]
+ export SYS_CONFIG_PATH=/opt/gwserver/releases/2.1.1/sys.config
+ export SRC_SYS_CONFIG_PATH=/opt/gwserver/releases/2.1.1/sys.config
+ [ /opt/gwserver/releases/2.1.1/sys.config != /opt/gwserver/var/sys.config ]
+ echo %% Generated - edit/create /opt/gwserver/sys.config instead.
+ cat /opt/gwserver/releases/2.1.1/sys.config
+ export SYS_CONFIG_PATH=/opt/gwserver/var/sys.config
+ [ ]
+ egrep ^-s?name /opt/gwserver/var/vm.args
+ export NAME_ARG=-name gwserver@127.0.0.1
+ [ -z -name gwserver@127.0.0.1 ]
+ echo -name gwserver@127.0.0.1
+ awk {print $1}
+ export NAME_TYPE=-name
+ echo -name gwserver@127.0.0.1
+ awk {print $2}
+ export NAME=gwserver@127.0.0.1
+ PIPE_DIR=/opt/gwserver/var/erl_pipes/gwserver@127.0.0.1/
+ _load_cookie
+ grep ^-setcookie /opt/gwserver/var/vm.args
+ COOKIE_ARG=-setcookie F(F;}Cp_*{iH@V7D!x0jxeTvCeAR<j*iLDU:LrlL1;0Lg$tU_B,AIE=;xK$H]ddQ
+ DEFAULT_COOKIE_FILE=/root/.erlang.cookie
+ [ -z -setcookie F(F;}Cp_*{iH@V7D!x0jxeTvCeAR<j*iLDU:LrlL1;0Lg$tU_B,AIE=;xK$H]ddQ ]
+ echo -setcookie F(F;}Cp_*{iH@V7D!x0jxeTvCeAR<j*iLDU:LrlL1;0Lg$tU_B,AIE=;xK$H]ddQ
+ awk {print $2}
+ COOKIE=F(F;}Cp_*{iH@V7D!x0jxeTvCeAR<j*iLDU:LrlL1;0Lg$tU_B,AIE=;xK$H]ddQ
+ export ROOTDIR=/opt/gwserver
+ export BINDIR=/opt/gwserver/erts-8.2/bin
+ export EMU=beam
+ export PROGNAME=erl
+ export LD_LIBRARY_PATH=/opt/gwserver/erts-8.2/lib:
+ export ERTS_LIB_DIR=/opt/gwserver/erts-8.2/../lib
+ CONSOLIDATED_DIR=/opt/gwserver/lib/gwserver-2.1.1/consolidated
+ cd /opt/gwserver
+ export DISTILLERY_TASK=stop
+ _check_cookie
+ [ -z F(F;}Cp_*{iH@V7D!x0jxeTvCeAR<j*iLDU:LrlL1;0Lg$tU_B,AIE=;xK$H]ddQ ]
+ [ -z F(F;}Cp_*{iH@V7D!x0jxeTvCeAR<j*iLDU:LrlL1;0Lg$tU_B,AIE=;xK$H]ddQ ]
+ _run_hooks_from_dir /opt/gwserver/releases/2.1.1/hooks/pre_stop.d
+ [ -d /opt/gwserver/releases/2.1.1/hooks/pre_stop.d ]
+ [ -f /opt/gwserver/releases/2.1.1/hooks/pre_stop.d/[0-9a-zA-Z]*.sh ]
+ continue
+ get_pid
+ nodetool rpcterms os getpid
+ command=rpcterms
+ shift
+ name=gwserver@127.0.0.1
+ /opt/gwserver/erts-8.2/bin/escript /opt/gwserver/bin/nodetool -name gwserver@127.0.0.1 -setcookie F(F;}Cp_*{iH@V7D!x0jxeTvCeAR<j*iLDU:LrlL1;0Lg$tU_B,AIE=;xK$H]ddQ rpcterms os getpid
+ output="132996"
+ echo "132996"
+ sed -e s/"//g
+ return 0
+ PID=132996
+ nodetool stop
+ command=stop
+ shift
+ name=gwserver@127.0.0.1
+ /opt/gwserver/erts-8.2/bin/escript /opt/gwserver/bin/nodetool -name gwserver@127.0.0.1 -setcookie F(F;}Cp_*{iH@V7D!x0jxeTvCeAR<j*iLDU:LrlL1;0Lg$tU_B,AIE=;xK$H]ddQ stop
ok
+ kill -s 0 132996
+
+ sleep 1
+ kill -s 0 132996
+
+ sleep 1
+ kill -s 0 132996
+
+ sleep 1
+ kill -s 0 132996
+
+ _run_hooks_from_dir /opt/gwserver/releases/2.1.1/hooks/post_stop.d
+ [ -d /opt/gwserver/releases/2.1.1/hooks/post_stop.d ]
+ [ -f /opt/gwserver/releases/2.1.1/hooks/post_stop.d/[0-9a-zA-Z]*.sh ]
+ continue
+ exit 0
```

**Comment by bitwalker** [comment] 2017-03-08 22:11
Do you have any hooks under `hooks/pre_stop.d` or `hooks/post_stop.d` for 2.1.1? It's possible the VM updates `start_erl.data` when it shuts down, in which case the only way to do the update properly is to stop, then unpack, then start, or use hot upgrades where ERTS does all of that for you.

**Comment by Hermanverschooten** [comment] 2017-03-08 22:18
No hooks I looked, all the folders under hooks are empty.  The thing is this only started after upgrading a number of deps this afternoon.

I just tried watching start_erl.data with `auditctl -w /opt/gwserver/releases/start_erl.data -p w` and this   gives following entries:
```
root@GratWiFi:/opt/gwserver# auditctl -w /opt/gwserver/releases/start_erl.data -p w
root@GratWiFi:/opt/gwserver# bin/gwserver stop
ok
root@GratWiFi:/opt/gwserver# ausearch -f /opt/gwserver/releases/start_erl.data
----
time->Wed Mar  8 23:12:10 2017
type=PROCTITLE msg=audit(1489011130.112:17): proctitle=2F62696E2F7368002F6F70742F67777365727665722F72656C65617365732F322E312E312F67777365727665722E73680073746F70
type=PATH msg=audit(1489011130.112:17): item=1 name="/opt/gwserver/releases/start_erl.data" inode=17566736 dev=103:00 mode=0100664 ouid=0 ogid=0 rdev=00:00 nametype=NORMAL
type=PATH msg=audit(1489011130.112:17): item=0 name="/opt/gwserver/releases/" inode=17563804 dev=103:00 mode=040775 ouid=0 ogid=0 rdev=00:00 nametype=PARENT
type=CWD msg=audit(1489011130.112:17):  cwd="/opt/gwserver"
type=SYSCALL msg=audit(1489011130.112:17): arch=c000003e syscall=2 success=yes exit=3 a0=55de07215be8 a1=241 a2=1b6 a3=7f051e7d0ba8 items=2 ppid=119069 pid=135014 auid=1000 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=pts0 ses=173 comm="gwserver.sh" exe="/bin/dash" key=(null)
----
time->Wed Mar  8 23:12:13 2017
type=PROCTITLE msg=audit(1489011133.392:18): proctitle=2F62696E2F7368002F6F70742F67777365727665722F72656C65617365732F322E302E372F67777365727665722E73680072706300696E69740073746F70
type=PATH msg=audit(1489011133.392:18): item=1 name="/opt/gwserver/releases/start_erl.data" inode=17566736 dev=103:00 mode=0100664 ouid=0 ogid=0 rdev=00:00 nametype=NORMAL
type=PATH msg=audit(1489011133.392:18): item=0 name="/opt/gwserver/releases/" inode=17563804 dev=103:00 mode=040775 ouid=0 ogid=0 rdev=00:00 nametype=PARENT
type=CWD msg=audit(1489011133.392:18):  cwd="/"
type=SYSCALL msg=audit(1489011133.392:18): arch=c000003e syscall=2 success=yes exit=3 a0=562610969be8 a1=241 a2=1b6 a3=7fba85803ba8 items=2 ppid=134036 pid=135121 auid=4294967295 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=(none) ses=4294967295 comm="gwserver.sh" exe="/bin/dash" key=(null)
----
time->Wed Mar  8 23:12:13 2017
type=PROCTITLE msg=audit(1489011133.592:19): proctitle=2F62696E2F7368002F6F70742F67777365727665722F72656C65617365732F322E302E372F67777365727665722E73680073746F70
type=PATH msg=audit(1489011133.592:19): item=1 name="/opt/gwserver/releases/start_erl.data" inode=17566736 dev=103:00 mode=0100664 ouid=0 ogid=0 rdev=00:00 nametype=NORMAL
type=PATH msg=audit(1489011133.592:19): item=0 name="/opt/gwserver/releases/" inode=17563804 dev=103:00 mode=040775 ouid=0 ogid=0 rdev=00:00 nametype=PARENT
type=CWD msg=audit(1489011133.592:19):  cwd="/"
type=SYSCALL msg=audit(1489011133.592:19): arch=c000003e syscall=2 success=yes exit=3 a0=55e5a4805be8 a1=241 a2=1b6 a3=7fec98a96ba8 items=2 ppid=1 pid=135178 auid=4294967295 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=(none) ses=4294967295 comm="gwserver.sh" exe="/bin/dash" key=(null)
----
time->Wed Mar  8 23:12:14 2017
type=PROCTITLE msg=audit(1489011134.080:24): proctitle=2F62696E2F7368002F6F70742F67777365727665722F72656C65617365732F322E302E372F67777365727665722E736800666F726567726F756E64
type=PATH msg=audit(1489011134.080:24): item=1 name="/opt/gwserver/releases/start_erl.data" inode=17566736 dev=103:00 mode=0100664 ouid=0 ogid=0 rdev=00:00 nametype=NORMAL
type=PATH msg=audit(1489011134.080:24): item=0 name="/opt/gwserver/releases/" inode=17563804 dev=103:00 mode=040775 ouid=0 ogid=0 rdev=00:00 nametype=PARENT
type=CWD msg=audit(1489011134.080:24):  cwd="/"
type=SYSCALL msg=audit(1489011134.080:24): arch=c000003e syscall=2 success=yes exit=3 a0=5583eacfebe8 a1=241 a2=1b6 a3=7f9c06fc2ba8 items=2 ppid=135248 pid=135259 auid=4294967295 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=(none) ses=4294967295 comm="gwserver.sh" exe="/bin/dash" key=(null)
root@GratWiFi:/opt/gwserver#
```

The only exe writing to it seems to be the script.

**Comment by Hermanverschooten** [comment] 2017-03-08 22:22
I just did another simple test. I commented out the line that writes to releases/start_erl.data (the script is the one before your commit) and adjusted the rel to 2.1.1 and stopped the program. the version remains at 2.1.1, so it is clearly something in the script.

**Comment by bitwalker** [comment] 2017-03-08 22:22
That definitely can't be the case, because if you look at the script, it is only ever touched once, and that's at the beginning when it detects ERTS, and would affect every subsequent use of ERTS_VSN and REL_VSN, which we would see when DEBUG_BOOT=true is set. So the only other thing which could be modifying it is either a hook, a custom command, or the Erlang VM itself.

**Comment by bitwalker** [comment] 2017-03-08 22:24
If it was that line which is causing it, we should see it in the verbose output. Could you throw some echo statements in there before/after and see what REL_VSN is?

**Comment by Hermanverschooten** [comment] 2017-03-08 22:24
Do you by any change have tmate?

**Comment by bitwalker** [comment] 2017-03-08 22:25
I don't unfortunately.

**Comment by Hermanverschooten** [comment] 2017-03-08 22:27
I just sent you a private message on slack.

**Comment by bitwalker** [comment] 2017-03-08 22:58
Since we've applied a workaround, I'm going to close this for now. If you ever trace down what's modifying that file, let me know!

**Closed by bitwalker** 2017-03-08 22:58 UTC
