### ISSUE TITLE
Existing file ownership not respected for sys.config/vm.args when REPLACE_OS_VARS is used

### ISSUE THREAD

**Issue by thehunmonkgroup** [bitwalker/distillery#412] opened 2018-05-08 23:55 UTC
### Steps to reproduce

1. Have sys.config/vm.args owned by non-root user.
2. Run helper script as root as follows:
```sh
export REPLACE_OS_VARS=true
export NODENAME=foo
export NODEHOST=127.0.0.1
export NODECOOKIE='somecookie'
./bin/poof remote_console
```
3. Observe sys.config/vm.args are now owned by root user.

### Description of issue

- What are the expected results?

Existing file ownership/permissions should be respected.

- What OS, Erlang/Elixir versions are you seeing this issue on?

1.6.4/20.3

- `rel/config.exs`:
```elixir
Path.join(["rel", "plugins", "*.exs"])
|> Path.wildcard()
|> Enum.map(&Code.eval_file(&1))

use Mix.Releases.Config,
    default_release: :default,
    default_environment: Mix.env()

environment :prod do
  set include_erts: true
  set include_src: false
  set cookie: :"XXXXXXXX"
  set vm_args: "rel/vm.args"
end

release :poof do
  set version: current_version(:poof)
  set applications: [
    :runtime_tools
  ]
end
```

I'm guessing this occurs because Distillery deletes the existing file and creates a new one from the overlay template. This unfortunately causes a problem when running the node as a non-root user via systemd.

I suppose I could modify my wrapper script to always run as the same user that runs the node via systemd, but it would be nice if Distillery didn't change the perms of already existing files, which is more the 'nix norm I think...

**Comment by bitwalker** [comment] 2018-05-09 00:07
There is a commit in master which will avoid writing files when a particular environment variable is set, intended for this use case, but it is not a guarantee, just a thing we try to adhere to. Is there some method we can use here to preserve permissions while writing files, i.e., if creating a file, as root, in a directory owned by another user or group, can we make sure the file we write shares those same permissions? I'm open to PRs or suggestions on this front, but in the meantime, the workaround would be to run the command as the service user, as you suggested.

**Comment by thehunmonkgroup** [comment] 2018-05-09 00:45
The scripts are bash-driven, right? If that's the case, I think something like this will do:

```sh
if [ -f /path/to/file ]; then
 > /path/to/file
else
  touch /path/to/file
fi

echo "$template_contents" > /path/to/file
```

The ```> /path/to/file``` completely empties an existing file, and touch of course creates an empty file. Then you just fill the file with the contents of the overlay.

**Comment by bitwalker** [comment] 2018-05-09 01:02
The problem is the `touch` bit, because it will create the file as the root user (in our scenario) if the root user happens to be the first user to run the script, which will later blow up on the non-root user. Everywhere in the scripts where we manipulate files on disk, we use `>` or `>>`, though there are some places we use `cp -a` or `mv` (for making and restoring backups respectively).

Ultimately what I'd like is a way to create files/directories using the user/group permissions applied to the parent directory they are created in, so rather than creating a new file owned by `root:root`, we would create it as `poof:poof`, even though we are root (assuming `poof:poof` is the owner of the release root directory). I'm not sure if this is possible, short of using `stat` + `chown` after the fact. That feels pretty hacky though.

**Comment by thehunmonkgroup** [comment] 2018-05-09 01:15
Are you sure it's an issue that ```touch``` would create the file as root?

In my scenario, all my builds are also done by the user running the systemd service, so the very initial deploy has the correct ownership, and as long as that's never changed, everything is a-ok...

I guess I don't see it as necessary to be overly smart about it, but instead simply don't alter something that already exists (beyond the file contents of course, which is necessary).

**Comment by bitwalker** [comment] 2018-06-29 16:20
I think I found the problem, which is that `_replace_os_vars` was writing a new file, `<source file>.bak`, writing the replacements to that file, then moving it over the original source file. I've made a change so that we copy the source file, preserving permissions, then truncate/rewrite that file with the replacements, before finally moving it over the original source - this will ensure permissions are preserved.

**Closed** 2018-06-29 16:46 UTC
Labels: bug:unexpected behaviour, os:*nix
