### ISSUE TITLE
Accessing modules from within conform schema does not work

### ISSUE THREAD

**Issue by GalaxyGorilla** [bitwalker/distillery#171] opened 2016-12-22 13:28 UTC
Hey, I am currently switching from exrm to distillery in my stack. Since I use some more complicated transformations in my schema file I 'outsourced' it to some modules in my application. However, in opposite to exrm those modules are not available using distillery. The error I get is `UndefinedFunctionError` because `module XY is not available`.

Not sure if this is even the right place for this issue. Just using `mix conform.effective` works fine, so I thought this is rather a problem in distillery.

**Comment by bitwalker** [comment] 2016-12-23 19:46
I suspect this is due to distillery explicitly setting the code paths to use, definitely fixable, just have to figure out the best way to do that. I'll look into it ASAP

**Comment by GalaxyGorilla** [comment] 2017-01-05 10:48
Hi @bitwalker ! Is there any progress? Sorry for asking so impatiently but this seems to be really the only thing (that I know of) that prevents me from switching to distillery :3.

**Comment by GalaxyGorilla** [comment] 2017-01-10 17:49
Setting `include_erts` to `true` in the environment fixes this issue even though I don't know why :/

**Comment by bitwalker** [comment] 2017-01-10 22:06
The main difference between `include_erts: true | path` vs `include_erts: false` is that in the latter case, ERTS is detected and code paths to the required ERTS libs are based on the detected ERTS path. The only time there would be an issue is if the .beam files in the release were compiled on a different version of Erlang, or if the detected ERTS was missing applications required by the release. Do you have a repo I can use to reproduce? I can take a look sooner rather than later if so.

**Comment by GalaxyGorilla** [comment] 2017-01-11 10:45
Sure, I created some minimal repo to reproduce this. See [HERE](https://github.com/GalaxyGorilla/distillery_test). There is some description on reproducing the errors in the README.

**Comment by bitwalker** [comment] 2017-02-17 16:25
@GalaxyGorilla I've pushed a fix for this to master of conform. Could you update and give it a shot? If it looks good to you, I'll publish a new release of conform.

**Comment by GalaxyGorilla** [comment] 2017-02-21 18:07
Hey @bitwalker ! Thanks for diving into this! I tested it with my little tool and for a fresh release build using 

'''
mix release --env=without_erts
'''

everything seems to be ok. However, if you switch to 'without_erts' after starting with

'''
mix release --env=with_erts
'''

then I get the following error:

'''
init terminating in do_boot (cannot expand $ERTS_LIB_DIR in bootfile)

Crash dump is being written to: erl_crash.dump...done
'''

Good to see that this works now with a fresh build, that should solve the problems I had :). Do you have any idea about the above error?

**Comment by bitwalker** [comment] 2017-02-21 21:35
I wonder if the reason for that error has something to do with the leftover ERTS being in the release build directory. I'll play around with that and see what the best thing to do there is - I suspect it's a bug in the boot script when detecting the ERTS to use.

**Comment by bitwalker** [comment] 2017-02-27 21:55
Found the problem, it is now fixed in 1.2.1

**Closed by bitwalker** 2017-02-27 21:55 UTC

**Comment by GalaxyGorilla** [comment] 2017-02-28 08:59
Cool! Thanks for doing this!
