### ISSUE TITLE
Determining the app name and version of the release for an umbrella app

### ISSUE THREAD

**Issue by lpil** [bitwalker/distillery#201] opened 2017-02-12 22:58 UTC
Hello!

I'm using distillery with [`mix_docker`](https://github.com/Recruitee/mix_docker/), a tool that will handle building the image in one docker container and then extracting the release to use in another more minimal image.
It has been designed with regular apps in mind rather than umbrellas, and I'm trying to get it working with both.

At one point it determines the path to the release using `Mix.Project.get.project[:version]` and `Mix.Project.get.project[:version]`, which return `nil` for an umbrella apps with the default configuration.

Seeing as the name and version known or generated by distillery I feel the best way to get this information is to ask distillery. Is there an API I can use to do this?

Thank you,
Louis

Related issue: https://github.com/Recruitee/mix_docker/issues/2

**Comment by bitwalker** [comment] 2017-02-12 23:16
Could you show me the workflow you have in mind? I can make a recommendation based on that, or make changes if necessary.

**Comment by lpil** [comment] 2017-02-12 23:25
Here is the changes I've made to mix_docker to get umbrella applications working with the mix + distillery default configuration.

https://github.com/Recruitee/mix_docker/pull/15/files#diff-3dafbe633963cc78cba87e665ddf5184

I just copied what distillery does. I would like to perhaps call a function here that would return the name and version of the configuration of the default distillery release.

**Comment by bitwalker** [comment] 2017-02-12 23:33
The problem is that the release being built may be one of many in the config, using one of many environments, and while there are defaults for both, one can selectively build a release for a specific environment using flags to the release task - mix_docker should support that somehow. I can add an API for querying information about the current config, and provide options for specifying a release and environment to use in the case of overrides, but mix_docker will need to expose that configuration to users so that you can pass that information through.

**Comment by lpil** [comment] 2017-02-12 23:43
That would be great thank you.

mix_docker is currently a simple tool and it's unclear if @teamon et al would like to make use of such an API, so perhaps this feature request could be noted but not acted on just yet. My image compiles now, so I'm happy, at least for now. It may be that this API is not needed by anyone rightnow.

**Comment by teamon** [comment] 2017-02-13 14:50
Hey @lpil, 

I admit the way we "discover" where the release package is located is a bit hacky. 
If there is a way to do it using distillery API, thus supporting umbrellas and multiple configurations I'm all for it. This just hasn't been a priority for us since we use only single distillery config per app.

**Comment by bitwalker** [comment] 2017-02-17 15:36
In master I've added a public API function, `Mix.Releases.Release.get`. Could you take a look and let me know if that will work for you?

**Comment by bitwalker** [comment] 2017-02-27 23:22
This API has been released in 1.2+, let me know if you need additional help on this front!

**Closed by bitwalker** 2017-02-27 23:22 UTC
Labels: enhancement

**Comment by lpil** [comment] 2017-02-28 12:13
Thank you!
