### ISSUE TITLE
{"init terminating in do_boot",{load_failed,[base64url]}}

### ISSUE THREAD

**Issue by imranismail** [bitwalker/distillery#449] opened 2018-08-02 12:22 UTC
### Steps to reproduce

mix.lock
```elixir
%{
  ...redacted
"base64url": {:hex, :base64url, "0.0.1", "36a90125f5948e3afd7be97662a1504b934dd5dac78451ca6e9abf85a10286be", [:rebar], []},
  ...redacted
}

```

rel/config.exs
```elixir
# Import all plugins from `rel/plugins`
# They can then be used by adding `plugin MyPlugin` to
# either an environment, or release definition, where
# `MyPlugin` is the name of the plugin module.
~w(rel plugins *.exs)
|> Path.join()
|> Path.wildcard()
|> Enum.map(&Code.eval_file(&1))

use Mix.Releases.Config,
    # This sets the default release built by `mix release`
    default_release: :default,
    # This sets the default environment used by `mix release`
    default_environment: Mix.env()

# For a full list of config options for both releases
# and environments, visit https://hexdocs.pm/distillery/configuration.html


# You may define one or more environments in this file,
# an environment's settings will override those of a release
# when building in that environment, this combination of release
# and environment configuration is called a profile

environment :dev do
  # If you are running Phoenix, you should make sure that
  # server: true is set and the code reloader is disabled,
  # even in dev mode.
  # It is recommended that you build with MIX_ENV=prod and pass
  # the --env flag to Distillery explicitly if you want to use
  # dev mode.
  set dev_mode: true
  set include_erts: false
  set cookie: :"redacted"
end

environment :prod do
  set include_erts: true
  set include_src: false
  set cookie: :"redacted"
end

# You may define one or more releases in this file.
# If you have not set a default release, or selected one
# when running `mix release`, the first release in the file
# will be used by default

release :platform do
  set version: "0.1.0"
  set applications: [
    :runtime_tools,
    ...redacted...
  ]
end
```

### Verbose Logs

Paste the output of the release command you ran with the `--verbose` flag
below in the summary tags (this helps keep the issue easy to navigate):

<summary>
  <details>

```sh
$ _build/dev/rel/platform/bin/platform console --verbose
{"init terminating in do_boot",{load_failed,[base64url]}}
init terminating in do_boot ({load_failed,[base64url]})

Crash dump is being written to: erl_crash.dump...done
```

  </details>
</summary>

### Description of issue

- What are the expected results?
Successfully initiating an iex session
- What version of Distillery?
2.0.0-rc.5
- What OS, Erlang/Elixir versions are you seeing this issue on?
MacOS 10.13.3

**Comment by imranismail** [comment] 2018-08-02 12:35
We were trying to upgrade our CD to use the new 2.0.0 in production but hit with this blocker and a few others that I've managed to resolve in #448 #446

**Comment by bitwalker** [comment] 2018-08-02 14:36
With the latest in master, I'm unable to reproduce this on macOS with a sample project (with both `include_erts: false` and `include_erts: true`). Is there something in particular I can do to reproduce? If you give me the set of deps you are using, I can try and test by at least building an app with the same dependency tree (more or less)

**Comment by imranismail** [comment] 2018-08-02 15:16
@bitwalker 

I've setup a project here https://github.com/imranismail/distillery_test

The issue happens when I include `guardian` as deps which has a dependency on `base65url`

Here's another interesting thing. When `guardian` is excluded in that project, there seems to be an issue with loading nif.

Here's the log from trying to fire up console

```shell
$ _build/dev/rel/distillery_test/bin/distillery_test console --verbose
Erlang/OTP 21 [erts-10.0.3] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe] [dtrace]

2018-08-02 23:14:29.671601
    args: [load_failed,"Failed to load NIF library: 'dlopen(/Users/imranismail/Projects/distillery_test/_build/dev/rel/distillery_test/lib/crypto-4.3/priv/lib/crypto.so, 2): image not found'","OpenSSL might not be installed on this system.\n"]
    format: "Unable to load crypto library. Failed with error:~n\"~p, ~s\"~n~s"
    label: {error_logger,error_msg}
2018-08-02 23:14:29.672880 crash_report        #{label=>{proc_lib,crash},report=>[[{initial_call,{supervisor,kernel,['Argument__1']}},{pid,<0.1251.0>},{registered_name,[]},{error_info,{exit,{on_load_function_failed,crypto},[{init,run_on_load_handlers,0,[]},{kernel,init,1,[{file,"kernel.erl"},{line,212}]},{supervisor,init,1,[{file,"supervisor.erl"},{line,295}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,374}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,342}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,249}]}]}},{ancestors,[kernel_sup,<0.1224.0>]},{message_queue_len,1},{messages,[{'$gen_call',{<0.1248.0>,#Ref<0.1688236519.1428946946.234381>},{start_child,{disk_log_sup,{disk_log_sup,start_link,[]},permanent,1000,supervisor,[disk_log_sup]}}}]},{links,[<0.1226.0>]},{dictionary,[]},{trap_exit,true},{status,running},{heap_size,610},{stack_size,27},{reductions,276}],[]]}
2018-08-02 23:14:29.672931 supervisor_report   #{label=>{supervisor,start_error},report=>[{supervisor,{local,kernel_sup}},{errorContext,start_error},{reason,{on_load_function_failed,crypto}},{offender,[{pid,undefined},{id,kernel_safe_sup},{mfargs,{supervisor,start_link,[{local,kernel_safe_sup},kernel,safe]}},{restart_type,permanent},{shutdown,infinity},{child_type,supervisor}]}]}
*** ERROR: Shell process terminated! (^G to start new job) ***
2018-08-02 23:14:30.678042 crash_report        #{label=>{proc_lib,crash},report=>[[{initial_call,{application_master,init,['Argument__1','Argument__2','Argument__3','Argument__4']}},{pid,<0.1223.0>},{registered_name,[]},{error_info,{exit,{{shutdown,{failed_to_start_child,kernel_safe_sup,{on_load_function_failed,crypto}}},{kernel,start,[normal,[]]}},[{application_master,init,4,[{file,"application_master.erl"},{line,138}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,249}]}]}},{ancestors,[<0.1222.0>]},{message_queue_len,0},{messages,[]},{links,[<0.1222.0>,<0.1224.0>,<0.1221.0>]},{dictionary,[]},{trap_exit,true},{status,running},{heap_size,610},{stack_size,27},{reductions,191}],[]]}
2018-08-02 23:14:30.680380 std_info            #{label=>{application_controller,exit},report=>[{application,kernel},{exited,{{shutdown,{failed_to_start_child,kernel_safe_sup,{on_load_function_failed,crypto}}},{kernel,start,[normal,[]]}}},{type,permanent}]}
{"Kernel pid terminated",application_controller,"{application_start_failure,kernel,{{shutdown,{failed_to_start_child,kernel_safe_sup,{on_load_function_failed,crypto}}},{kernel,start,[normal,[]]}}}"}
Kernel pid terminated (application_controller) ({application_start_failure,kernel,{{shutdown,{failed_to_start_child,kernel_safe_sup,{on_load_function_failed,crypto}}},{kernel,start,[normal,[]]}}})

Crash dump is being written to: erl_crash.dump...done
```

**Comment by imranismail** [comment] 2018-08-02 15:17
Might be related to https://github.com/bitwalker/distillery/issues/436

**Comment by imranismail** [comment] 2018-08-02 15:19
Some information on deps tree that might be helpful

```
==> web
web
├── gettext ~> 0.11 (Hex package)
├── phoenix_pubsub ~> 1.0 (Hex package)
├── cowboy ~> 1.0 (Hex package)
│   ├── cowlib ~> 1.0.2 (Hex package)
│   └── ranch ~> 1.3.2 (Hex package)
├── phoenix_html ~> 2.10 (Hex package)
│   └── plug ~> 1.5 (Hex package)
│       ├── cowboy ~> 1.0.1 or ~> 1.1 or ~> 2.4 (Hex package)
│       └── mime ~> 1.0 (Hex package)
├── phoenix ~> 1.3.3 (Hex package)
│   ├── cowboy ~> 1.0 (Hex package)
│   ├── phoenix_pubsub ~> 1.0 (Hex package)
│   ├── plug ~> 1.3.3 or ~> 1.4 (Hex package)
│   └── poison ~> 2.2 or ~> 3.0 (Hex package)
├── phoenix_live_reload ~> 1.0 (Hex package)
│   ├── file_system ~> 0.2.1 or ~> 0.3 (Hex package)
│   └── phoenix ~> 1.0 or ~> 1.2 or ~> 1.3 (Hex package)
├── guardian ~> 1.0 (Hex package)
│   ├── jose ~> 1.8 (Hex package)
│   │   └── base64url ~> 0.0.1 (Hex package)
│   ├── phoenix ~> 1.0 or ~> 1.2 or ~> 1.3 (Hex package)
│   ├── plug ~> 1.3.3 or ~> 1.4 (Hex package)
│   ├── poison ~> 2.2 or ~> 3.0 (Hex package)
│   └── uuid >= 1.1.1 (Hex package)
└── phoenix_ecto ~> 3.2 (Hex package)
    ├── ecto ~> 2.1 (Hex package)
    │   ├── decimal ~> 1.2 (Hex package)
    │   ├── poison ~> 2.2 or ~> 3.0 (Hex package)
    │   └── poolboy ~> 1.5 (Hex package)
    ├── phoenix_html ~> 2.9 (Hex package)
    └── plug ~> 1.0 (Hex package)
```

**Comment by bitwalker** [comment] 2018-08-02 16:27
This has been resolved in master, it was an issue with the code path being stripped accidentally. I'll be cutting a new release shortly.

**Closed** 2018-08-02 16:26 UTC
Labels: 2.0, investigating, investigating:can't reproduce
