### ISSUE TITLE
Problem during upgrade (eheap_alloc error)

### ISSUE THREAD

**Issue by dsl2014** [bitwalker/distillery#248] opened 2017-04-12 08:56 UTC
first:
     ./bin/app console    (current verison 0.0.1)
next: 
  dx@ubuntu:~/work/local_deploy$ ./bin/eazy_poker upgrade 0.0.2
      Release 0.0.2 is already unpacked
      Release 0.0.2 is already unpacked, now installing.
     escript: exception error: no case clause matching {badrpc,nodedown}

running version 0.0.1 have error : eheap_alloc: Cannot allocate 2733560184 bytes of memory (of type "heap").

**Comment by bitwalker** [comment] 2017-04-12 17:06
This looks to be an environmental issue - it's not clear to me what is being upgraded, but it seems either 0.0.1 has a memory leak, or the new code in 0.0.2 is triggering an unbounded allocation during the upgrade causing it to fail. Do you have a repo I can checkout to reproduce?

**Comment by dsl2014** [comment] 2017-04-13 01:43
environmental issue?  config? example: prod.exs have issue?    this project no open,  so no repo ,sorry

**Comment by dsl2014** [comment] 2017-04-13 01:51
xx@ubuntu:~/work/local_deploy$ ./bin/poker upgrade 0.0.2Node is not running!
xx@ubuntu:~/work/local_deploy$ ./bin/poker upgrade 0.0.2
escript: exception error: bad generator 
                 {badrpc,
                     {'EXIT',
                         {noproc,
                             {gen_server,call,
                                 [release_handler,which_releases,infinity]}}}}
xx@ubuntu:~/work/local_deploy$

**Comment by dsl2014** [comment] 2017-04-13 02:57
In hot time, the memory and cpu when high and low， finally， ｛badrpc, timeout｝

**Comment by bitwalker** [comment] 2018-03-10 00:06
It seems this has not come up again since reported. I'm going to close this for now, but if you come to this issue because you have just encountered it, please provide as much information and context as possible!

**Closed by bitwalker** 2018-03-10 00:06 UTC
Labels: cannot reproduce
