### ISSUE TITLE
REPLACE_OS_VARS=true does not seem to be working?

### ISSUE THREAD

**Issue by selfup** [bitwalker/distillery#408] opened 2018-04-14 16:03 UTC
### Steps to reproduce

```elixir
# config.exs

set cookie: :"base_cookie_will_be_changed_at_runtime"
set vm_args: "./rel/vm.args"
```

```
#vm.args
-name foo@127.0.0.1

-setcookie okok
```

Everything is fine, long name is set correctly

***

```
#vm.args

-name foo@127.0.0.1

-setcookie ${COOKIE}
```

Panic about cookie not being set

***

```
#vm.args
-sname ${NAME_SNAME_IP}
```

`REPLACE_OS_VARS=true` is set prior to running the bin

https://github.com/selfup/smache/blob/docker_discovery/rel/vm_args.exs

The first 3 lines in the output are from the `vm_args.exs` script showing that the ENV VARS are set correctly:

```log
prod_1  | "79dd856c9f6@172.25.0.2"
prod_1  | "true"
prod_1  | "5CB1B6E9ABDFD45E32A2D6B12467C96A37821D06ADC3FD7788E4EF15D725FA84"
prod_1  | 2018-04-14 15:59:12 Can't set long node name!
```

Last line is the `long node name` error

It is not reading the VARS?

### Just a brief list of the steps required to produce the issue.

Clone: https://github.com/selfup/smache

`git checkout docker_discovery`

`./scripts/smache.sh`

### Verbose Logs

Paste the output of the release command you ran with the `--verbose` flag.

```log
prod_1  | 2018-04-14 15:59:12 Can't set long node name!
prod_1  | Please check your configuration
prod_1  |
prod_1  | 2018-04-14 15:59:12 crash_report
prod_1  |     initial_call:     pid:     registered_name:     error_info:     ancestors:     message_queue_len:     messages:     links:     dictionary:     trap_exit:     status:     heap_size:     stack_size:     reductions: 2018-04-14 15:59:12 supervisor_report
prod_1  |     supervisor:     errorContext:     reason:     offender: 2018-04-14 15:59:12 supervisor_report
prod_1  |     supervisor:     errorContext:     reason:     offender: 2018-04-14 15:59:12 crash_report
prod_1  |     initial_call:     pid:     registered_name:     error_info:     ancestors:     message_queue_len:     messages:     links:     dictionary:     trap_exit:     status:     heap_size:     stack_size:     reductions: 2018-04-14 15:59:12 std_info
prod_1  |     application:     exited:     type: Kernel pid terminated (application_controller) ({application_start_failure,kernel,{{shutdown,{failed_to_start_child,net_sup,{shutdown,{failed_to_start_child,net_kernel,{'EXIT',nodistribution}}}}},{ker
prod_1  |
prod_1  | Crash dump is being written to: erl_crash.dump...done
```

### Description of issue

- What are the expected results? _That the ENV VARS are read at runtime_
- What OS, Erlang/Elixir versions are you seeing this issue on? _OS: Alpine Linux - Elixir: 1.6.3_ **Docker image is:** `FROM bitwalker/alpine-elixir:1.6.3`
- If possible, also provide your `rel/config.exs`, as it is often
  my first troubleshooting question, and you'll save us both time :)

https://github.com/selfup/smache/blob/docker_discovery/rel/config.exs

- Is there documentation that says one thing, but Distillery does
  another? If so, please link the doc here so it can be updated if
  it's a documentation issue, or so that the fix can be based around
  what's documented.

https://hexdocs.pm/distillery/runtime-configuration.html#vm-args

**Comment by selfup** [comment] 2018-04-15 00:50
Ok seems I found a fix. Feels a bit dirty...

Have the `exs` script export a string...

```elixir
IO.puts "export SNAME_IP=#{name}@#{ip} export COOKIE=#{cookie}"
```

Make a script that:

_evaluates the output in bash and then run the app_

```bash
$(elixir rel/vm_args.exs)
echo $COOKIE
echo $SNAME_IP
_build/prod/rel/smache/bin/smache foreground
```

It seems that `System.put_env` does not persist

***

Anything more elegant than this? Or is this about right?

**Comment by selfup** [comment] 2018-04-15 14:38
Maybe we can add in the documentation that inside of a Container:

1. `source`
1. `System.put_env`

Don't work and that you must 

1. `export` 

Prior to running the binary?

**Comment by selfup** [comment] 2018-04-16 02:08
Going to close. Let me know if I should update docs or not 🙏

**Comment by selfup** [comment] 2018-04-21 18:56
Seems another person is running into this on the Elixir Slack (docker/alpine)

**Comment by selfup** [comment] 2018-04-21 19:03
```
wackyzacck [4 minutes ago]
distillery not recieving the variable


wackyzacck [4 minutes ago]
or docker-compose not sending the variable


selfup [4 minutes ago]
yea it's still good to discover through that issue maybe


wackyzacck [3 minutes ago]
We need to know where we are losing the variable
```

Summary of what we have run into

**Comment by bitwalker** [comment] 2018-05-09 00:14
I'm not sure I follow what the issue is exactly, are you expecting to run an Elixir script and have it modify the callers environment? I'm going to close this, but feel free to keep the discussion going, if I feel there is a task here I will reopen, or open a new issue.

**Closed by bitwalker** 2018-05-09 00:14 UTC

**Comment by selfup** [comment] 2018-05-09 00:16
Ok no worries, thanks for looking into it. I got it to work fine with the elixir script, but others ran into weird stuff with docker-compoze and env vars

Thanks 🙏
