### ISSUE TITLE
mv: cannot stat ''/srv/apps/app_name/var/vm.args.bak': No such file or directory

### ISSUE THREAD

**Issue by lessless** [bitwalker/distillery#275] opened 2017-06-08 17:25 UTC
### Steps to reproduce

I would love to receive any tips about debugging but so far it's
 `mix edeliver update staging --start-deploy --branch=master --verbose`.
According to the error message, I assume that it occurs during `./bin/app_name upgrade ...` command

### Verbose Logs

```
==> Loading configuration..
==> Assembling release..
==> Building release app_name:0.1.1128+3e42305 using environment prod
==> One or more direct or transitive dependencies are missing from
    :applications or :included_applications, they will not be included
    in the release:

    :elixir_make

    This can cause your application to fail at runtime. If you are sure
    that this is not an issue, you may ignore this warning.

==> Discovered applications:
  mail-0.1.1
    from: _build/prod/lib/mail
    applications:
      :kernel
      :stdlib
      :elixir
      :logger
    includes: none

  poolboy-1.5.1
    from: _build/prod/lib/poolboy
    applications:
      :kernel
      :stdlib
    includes: none

  ecto-2.1.4
    from: _build/prod/lib/ecto
    applications:
      :kernel
      :stdlib
      :elixir
      :logger
      :decimal
      :poolboy
    includes: none

  phoenix_ecto-3.2.3
    from: _build/prod/lib/phoenix_ecto
    applications:
      :kernel
      :stdlib
      :elixir
      :logger
      :ecto
      :plug
    includes: none

  scrivener-2.3.0
    from: _build/prod/lib/scrivener
    applications:
      :kernel
      :stdlib
      :elixir
      :logger
    includes: none

  scrivener_ecto-1.1.4
    from: _build/prod/lib/scrivener_ecto
    applications:
      :kernel
      :stdlib
      :elixir
      :scrivener
      :logger
    includes: none

  edeliver-1.4.2
    from: _build/prod/lib/edeliver
    applications:
      :kernel
      :stdlib
      :elixir
    includes: none

  distillery-1.4.0
    from: _build/prod/lib/distillery
    applications:
      :kernel
      :stdlib
      :elixir
    includes: none

  crontab-1.0.0
    from: _build/prod/lib/crontab
    applications:
      :kernel
      :stdlib
      :elixir
      :logger
      :timex
    includes: none

  calendar-0.17.2
    from: _build/prod/lib/calendar
    applications:
      :kernel
      :stdlib
      :elixir
      :logger
      :tzdata
    includes: none

  quantum-1.9.2
    from: _build/prod/lib/quantum
    applications:
      :kernel
      :stdlib
      :elixir
      :calendar
      :crontab
    includes: none

  arc_ecto-0.6.0
    from: _build/prod/lib/arc_ecto
    applications:
      :kernel
      :stdlib
      :elixir
      :logger
    includes: none

  connection-1.0.4
    from: _build/prod/lib/connection
    applications:
      :kernel
      :stdlib
      :elixir
    includes: none

  db_connection-1.1.2
    from: _build/prod/lib/db_connection
    applications:
      :kernel
      :stdlib
      :elixir
      :logger
      :connection
    includes: none

  postgrex-0.13.2
    from: _build/prod/lib/postgrex
    applications:
      :kernel
      :stdlib
      :elixir
      :logger
      :db_connection
      :decimal
      :crypto
    includes: none

  scrivener_html-1.6.0
    from: _build/prod/lib/scrivener_html
    applications:
      :kernel
      :stdlib
      :elixir
      :logger
    includes: none

  slime-0.16.0
    from: _build/prod/lib/slime
    applications:
      :kernel
      :stdlib
      :elixir
      :eex
    includes: none

  phoenix_slime-0.8.0
    from: _build/prod/lib/phoenix_slime
    applications:
      :kernel
      :stdlib
      :elixir
      :phoenix
      :slime
    includes: none

  eex-1.4.4
    from: /usr/local/lib/elixir/bin/../lib/eex
    applications:
      :kernel
      :stdlib
      :elixir
    includes: none

  phoenix-1.2.3
    from: _build/prod/lib/phoenix
    applications:
      :kernel
      :stdlib
      :elixir
      :plug
      :poison
      :logger
      :eex
    includes: none

  mime-1.1.0
    from: _build/prod/lib/mime
    applications:
      :kernel
      :stdlib
      :elixir
    includes: none

  plug-1.3.4
    from: _build/prod/lib/plug
    applications:
      :kernel
      :stdlib
      :elixir
      :crypto
      :logger
      :mime
    includes: none

  phoenix_html-2.9.3
    from: _build/prod/lib/phoenix_html
    applications:
      :kernel
      :stdlib
      :elixir
      :logger
      :plug
    includes: none

  cowlib-1.0.2
    from: _build/prod/lib/cowlib
    applications:
      :kernel
      :stdlib
      :crypto
    includes: none

  ranch-1.3.2
    from: _build/prod/lib/ranch
    applications:
      :kernel
      :stdlib
      :ssl
    includes: none

  cowboy-1.1.2
    from: _build/prod/lib/cowboy
    applications:
      :kernel
      :stdlib
      :ranch
      :cowlib
      :crypto
    includes: none

  syntax_tools-2.1.1
    from: /usr/lib/erlang/lib/syntax_tools-2.1.1
    applications:
      :stdlib
    includes: none

  inets-6.3.4
    from: /usr/lib/erlang/lib/inets-6.3.4
    applications:
      :kernel
      :stdlib
    includes: none

  mochiweb-2.12.2
    from: _build/prod/lib/mochiweb
    applications:
      :kernel
      :stdlib
      :crypto
      :inets
      :ssl
      :xmerl
      :compiler
      :syntax_tools
    includes: none

  html_sanitize_ex-1.0.1
    from: _build/prod/lib/html_sanitize_ex
    applications:
      :kernel
      :stdlib
      :elixir
      :logger
      :mochiweb
    includes: none

  phoenix_pubsub-1.0.1
    from: _build/prod/lib/phoenix_pubsub
    applications:
      :kernel
      :stdlib
      :elixir
      :logger
      :crypto
    includes: none

  stripity_stripe-1.4.0
    from: _build/prod/lib/stripity_stripe
    applications:
      :kernel
      :stdlib
      :elixir
      :httpoison
    includes: none

  httpoison-0.11.1
    from: _build/prod/lib/httpoison
    applications:
      :kernel
      :stdlib
      :elixir
      :hackney
    includes: none

  arc-0.7.0
    from: _build/prod/lib/arc
    applications:
      :kernel
      :stdlib
      :elixir
      :logger
      :httpoison
    includes: none

  ex_aws-1.2.0
    from: _build/prod/lib/ex_aws
    applications:
      :kernel
      :stdlib
      :elixir
      :logger
      :crypto
    includes: none

  xmerl-1.3.12
    from: /usr/lib/erlang/lib/xmerl-1.3.12
    applications:
      :kernel
      :stdlib
    includes: none

  sweet_xml-0.6.5
    from: _build/prod/lib/sweet_xml
    applications:
      :kernel
      :stdlib
      :elixir
      :xmerl
    includes: none

  combine-0.9.6
    from: _build/prod/lib/combine
    applications:
      :kernel
      :stdlib
      :elixir
    includes: none

  metrics-1.0.1
    from: _build/prod/lib/metrics
    applications:
      :kernel
      :stdlib
    includes: none

  ssl_verify_fun-1.1.1
    from: _build/prod/lib/ssl_verify_fun
    applications:
      :kernel
      :stdlib
      :ssl
    includes: none

  certifi-1.0.0
    from: _build/prod/lib/certifi
    applications:
      :kernel
      :stdlib
    includes: none

  mimerl-1.0.2
    from: _build/prod/lib/mimerl
    applications:
      :kernel
      :stdlib
    includes: none

  idna-4.0.0
    from: _build/prod/lib/idna
    applications:
      :kernel
      :stdlib
    includes: none

  ssl-8.1
    from: /usr/lib/erlang/lib/ssl-8.1
    applications:
      :crypto
      :public_key
      :kernel
      :stdlib
    includes: none

  public_key-1.3
    from: /usr/lib/erlang/lib/public_key-1.3
    applications:
      :asn1
      :crypto
      :kernel
      :stdlib
    includes: none

  asn1-4.0.4
    from: /usr/lib/erlang/lib/asn1-4.0.4
    applications:
      :kernel
      :stdlib
    includes: none

  hackney-1.7.1
    from: _build/prod/lib/hackney
    applications:
      :kernel
      :stdlib
      :crypto
      :asn1
      :public_key
      :ssl
      :idna
      :mimerl
      :certifi
      :ssl_verify_fun
      :metrics
    includes: none

  tzdata-0.5.11
    from: _build/prod/lib/tzdata
    applications:
      :kernel
      :stdlib
      :elixir
      :hackney
      :logger
    includes: none

  timex-3.1.13
    from: _build/prod/lib/timex
    applications:
      :kernel
      :stdlib
      :elixir
      :logger
      :tzdata
      :gettext
      :combine
    includes: none

  gen_stage-0.11.0
    from: _build/prod/lib/gen_stage
    applications:
      :kernel
      :stdlib
      :elixir
      :logger
    includes: none

  flow-0.11.1
    from: _build/prod/lib/flow
    applications:
      :kernel
      :stdlib
      :elixir
      :logger
      :gen_stage
    includes: none

  parallel_stream-1.0.5
    from: _build/prod/lib/parallel_stream
    applications:
      :kernel
      :stdlib
      :elixir
    includes: none

  csv-1.4.4
    from: _build/prod/lib/csv
    applications:
      :kernel
      :stdlib
      :elixir
      :parallel_stream
    includes: none

  crypto-3.7.2
    from: /usr/lib/erlang/lib/crypto-3.7.2
    applications:
      :kernel
      :stdlib
    includes: none

  comeonin-3.0.2
    from: _build/prod/lib/comeonin
    applications:
      :kernel
      :stdlib
      :elixir
      :crypto
      :logger
    includes: none

  decimal-1.3.1
    from: _build/prod/lib/decimal
    applications:
      :kernel
      :stdlib
      :elixir
    includes: none

  poison-2.2.0
    from: _build/prod/lib/poison
    applications:
      :kernel
      :stdlib
      :elixir
    includes: none

  ex_cldr-0.2.0
    from: _build/prod/lib/ex_cldr
    applications:
      :kernel
      :stdlib
      :elixir
      :poison
      :decimal
    includes: none

  gettext-0.13.1
    from: _build/prod/lib/gettext
    applications:
      :kernel
      :stdlib
      :elixir
      :logger
    includes: none

  murmur-1.0.0
    from: _build/prod/lib/murmur
    applications:
      :kernel
      :stdlib
      :elixir
    includes: none

  runtime_tools-1.11
    from: /usr/lib/erlang/lib/runtime_tools-1.11
    applications:
      :kernel
      :stdlib
    includes: none

  logger-1.4.4
    from: /usr/local/lib/elixir/bin/../lib/logger
    applications:
      :kernel
      :stdlib
      :elixir
    includes: none

  compiler-7.0.3
    from: /usr/lib/erlang/lib/compiler-7.0.3
    applications:
      :kernel
      :stdlib
    includes: none

  elixir-1.4.4
    from: /usr/local/lib/elixir/bin/../lib/elixir
    applications:
      :kernel
      :stdlib
      :compiler
    includes: none

  stdlib-3.2
    from: /usr/lib/erlang/lib/stdlib-3.2
    applications:
      :kernel
    includes: none

  kernel-5.1.1
    from: /usr/lib/erlang/lib/kernel-5.1.1
    applications: none
    includes: none

  app_name-0.1.1128+3e42305
    from: _build/prod/lib/app_name
    applications:
      :kernel
      :stdlib
      :elixir
      :logger
      :runtime_tools
      :murmur
      :gettext
      :ex_cldr
      :comeonin
      :csv
      :flow
      :timex
      :sweet_xml
      :ex_aws
      :arc
      :stripity_stripe
      :phoenix_pubsub
      :html_sanitize_ex
      :cowboy
      :phoenix_html
      :phoenix
      :phoenix_slime
      :scrivener_html
      :postgrex
      :arc_ecto
      :quantum
      :distillery
      :edeliver
      :scrivener_ecto
      :phoenix_ecto
    includes: none

  iex-1.4.4
    from: /usr/local/lib/elixir/bin/../lib/iex
    applications:
      :kernel
      :stdlib
      :elixir
    includes: none

  sasl-3.0.2
    from: /usr/lib/erlang/lib/sasl-3.0.2
    applications:
      :kernel
      :stdlib
    includes: none

  postman-0.1.0
    from: _build/prod/lib/postman
    applications:
      :kernel
      :stdlib
      :elixir
      :logger
      :ex_aws
      :gen_stage
      :timex
      :distillery
      :mail
      :app_name
    includes: none

==> Generated overlay vars:
    release_name=:app_name
    release_version="0.1.1128+3e42305"
    is_upgrade=false
    upgrade_from=:latest
    dev_mode=false
    include_erts=true
    include_src=false
    include_system_libs=true
    erl_opts=""
    run_erl_env=""
    erts_vsn="8.2"
    output_dir="_build/prod/rel/app_name"
==> Copying applications to _build/prod/rel/app_name
==> Generating nodetool
==> Generating start_erl.data
==> Generating vm.args
==> Generating sys.config from config/config.exs
==> Including ERTS 8.2 from /usr/lib/erlang/erts-8.2
==> Generating boot script
==> Generating RELEASES
==> Generating start_clean.boot
==> Applying overlays
==> Applying mkdir overlay
    dst: releases/0.1.1128+3e42305/hooks
==> Applying mkdir overlay
    dst: releases/0.1.1128+3e42305/hooks/pre_configure.d
==> Applying mkdir overlay
    dst: releases/0.1.1128+3e42305/hooks/pre_start.d
==> Applying mkdir overlay
    dst: releases/0.1.1128+3e42305/hooks/post_start.d
==> Applying mkdir overlay
    dst: releases/0.1.1128+3e42305/hooks/pre_stop.d
==> Applying mkdir overlay
    dst: releases/0.1.1128+3e42305/hooks/post_stop.d
==> Applying mkdir overlay
    dst: releases/0.1.1128+3e42305/hooks/pre_upgrade.d
==> Applying mkdir overlay
    dst: releases/0.1.1128+3e42305/hooks/post_upgrade.d
==> Applying mkdir overlay
    dst: releases/0.1.1128+3e42305/commands
==> Packaging release..
==> Archiving app_name-0.1.1128+3e42305
==> Writing tarball to _build/prod/rel/app_name/releases/0.1.1128+3e42305/app_name.tar.gz
==> Updating tarball
==> Tarball updated!
==> Release successfully built!
    You can run it in one of the following ways:
      Interactive: _build/prod/rel/app_name/bin/app_name console
      Foreground: _build/prod/rel/app_name/bin/app_name foreground
      Daemon: _build/prod/rel/app_name/bin/app_name start
```

### Description of issue
There is an 
```
mv: cannot stat '/srv/apps/flowmail_web/var/vm.args.bak': No such file or directory
```
error during deploy and node doesn't start .  Supposedly it happens here https://github.com/bitwalker/distillery/blob/master/priv/templates/boot.eex#L612

- What are the expected results?
Deploy finishes without error 

- What OS, Erlang/Elixir versions are you seeing this issue on?

Erlang/OTP 19 [erts-8.2] [source] [64-bit] [smp:2:2] [async-threads:10] [kernel-poll:false]
Elixir 1.4.4

- If possible, also provide your `rel/config.exs`, as it is often
  my first troubleshooting question, and you'll save us both time :)

```
use Mix.Releases.Config,
    default_release: :app_name,
    default_environment: :prod

environment :dev do
  set dev_mode: true
  set include_erts: false
  set cookie: :"cookie"
end

environment :prod do
  set include_erts: true
  set include_src: false
  set cookie: :"cookie"
end

release :app_name do
  set version: current_version(:app_name)
  set applications: [
    app_name: :permanent,
    postman: :permanent
  ]
end
```
- Is there documentation that says one thing, but Distillery does
  another? If so, please link the doc here so it can be updated if
  it's a documentation issue, or so that the fix can be based around
  what's documented.

No

- Distillery version `1.4.0`

UPDATE: it's an umbrella app

**Comment by bitwalker** [comment] 2017-06-14 02:32
The script crashes on line 613 for sure? Because if so, that implies a previous upgrade failed, and the `.bak` file for `vm.args` is still present (so we restore the backup and proceed). It seems much more likely that later on, just after that, the copies of the originals to their corresponding `.bak` files fails silently and the subsequent `mv` fails because they don't exist. Alternatively it's a permissions issue, and the `.bak` can't be read/written because it was written by a different user.

I just merged a PR which ensures symlinks are handled properly there, so you may want to give that a shot if the above doesn't turn out any leads. Unfortunately with the information at hand, it's not clear what went wrong. You could also try running the upgrade with `DEBUG_BOOT=true` to see verbose output of what the boot script is doing, and where it fails (it is noisy, but if something is failing, that's the best way to find out).

**Comment by lessless** [comment] 2017-06-19 01:39
> It seems much more likely that later on, just after that, the copies of the originals to their corresponding .bak files fails silently and the subsequent mv fails because they don't exist.

That very well might be it! All, after all, it is really weird to an error in that `if` condition. I just tried a master branch and it didn't help.  

Also, it happens that we are using `edeliver` to deploy the app so applying `DEBUG_TRUE` option may require extra steps. So far I tried downgrading and upgrading releases but couldn't hit the problem as it kinda floating: 

```
<prev_ver>$ rm vm.args.bak
<prev_ver>$ DEBUG_BOOT=true ./flowmail_web.sh downgrade <prev_ver>


+ [ -f /srv/apps/flowmail_web/releases/<prev-ver>/sys.config.bak ]
+ [ -f /srv/apps/flowmail_web/releases/<prev-ver>/vm.args.bak ]
+ cp /srv/apps/flowmail_web/releases/<prev-ver>/sys.config /srv/apps/flowmail_web/releases/<prev-ver>/sys.config.bak
+ cp /srv/apps/flowmail_web/releases/<prev-ver>/vm.args /srv/apps/flowmail_web/releases/<prev-ver>/vm.args.bak
+ cp /srv/apps/flowmail_web/var/sys.config /srv/apps/flowmail_web/releases/<prev-ver>/sys.config
+ cp /srv/apps/flowmail_web/var/vm.args /srv/apps/flowmail_web/releases/<prev-ver>/vm.args
```


```
<prev_ver>$ DEBUG_BOOT=true ./flowmail_web.sh upgrade <next-ver>

 [ -f /srv/apps/flowmail_web/releases/<next-ver>/sys.config.bak ]
+ [ -f /srv/apps/flowmail_web/releases/<next-ver>/vm.args.bak ]
+ cp /srv/apps/flowmail_web/releases/<next-ver>/sys.config /srv/apps/flowmail_web/releases/<next-ver>/sys.config.bak
+ cp /srv/apps/flowmail_web/releases/<next-ver>/vm.args /srv/apps/flowmail_web/releases/<next-ver>/vm.args.bak
+ cp /srv/apps/flowmail_web/var/sys.config /srv/apps/flowmail_web/releases/<next-ver>/sys.config
```

I'm also thinking about modifying `edeliver` scripts to apply `DEBUG_BOOT` automatically, maybe that will help.

**Comment by bitwalker** [comment] 2017-06-19 17:23
Can you gist the entire output with `DEBUG_BOOT=true` (all you need to do in order to use it with edeliver is ensure that somewhere in the environment of the context where the release is running, that environment variable is set. That can be inline for a single command, set globally for a single shell session - as long as it's present, the boot script will pick it up.

You'll want to be sure that you look it over for anything sensitive which may leak, but as far as I'm aware nothing sensitive (other than node cookies) is ever explicitly passed on the command line, so you should be good to go.

**Comment by lessless** [comment] 2017-06-22 02:35
@bitwalker  got it!

```
+ grep -q Darwin
+ uname
+ readlink -f /srv/apps/flowmail_web/releases/0.1.1218+f5232ba/flowmail_web.sh
+ SCRIPT=/srv/apps/flowmail_web/releases/0.1.1218+f5232ba/flowmail_web.sh
+ dirname /srv/apps/flowmail_web/releases/0.1.1218+f5232ba/flowmail_web.sh
+ SCRIPT_DIR=/srv/apps/flowmail_web/releases/0.1.1218+f5232ba
+ dirname /srv/apps/flowmail_web/releases/0.1.1218+f5232ba
+ dirname /srv/apps/flowmail_web/releases
+ RELEASE_ROOT_DIR=/srv/apps/flowmail_web
+ RUN_ERL_DISABLE_FLOWCNTRL=true
+ REL_NAME=flowmail_web
+ REL_VSN=0.1.1218+f5232ba
+ ERTS_VSN=8.2
+ CODE_LOADING_MODE=embedded
+ START_ERL_DATA=/srv/apps/flowmail_web/releases/start_erl.data
+ REL_DIR=/srv/apps/flowmail_web/releases/0.1.1218+f5232ba
+ REL_LIB_DIR=/srv/apps/flowmail_web/lib
+ ERL_OPTS=
+ RUN_ERL_ENV=
+ RELEASE_MUTABLE_DIR=/srv/apps/flowmail_web/var
+ RUNNER_LOG_DIR=/srv/apps/flowmail_web/var/log
+ EXTRA_OPTS=
+ PRE_CONFIGURE_HOOKS=/srv/apps/flowmail_web/releases/0.1.1218+f5232ba/hooks/pre_configure.d
+ PRE_START_HOOKS=/srv/apps/flowmail_web/releases/0.1.1218+f5232ba/hooks/pre_start.d
+ POST_START_HOOKS=/srv/apps/flowmail_web/releases/0.1.1218+f5232ba/hooks/post_start.d
+ PRE_STOP_HOOKS=/srv/apps/flowmail_web/releases/0.1.1218+f5232ba/hooks/pre_stop.d
+ POST_STOP_HOOKS=/srv/apps/flowmail_web/releases/0.1.1218+f5232ba/hooks/post_stop.d
+ PRE_UPGRADE_HOOKS=/srv/apps/flowmail_web/releases/0.1.1218+f5232ba/hooks/pre_upgrade.d
+ POST_UPGRADE_HOOKS=/srv/apps/flowmail_web/releases/0.1.1218+f5232ba/hooks/post_upgrade.d
+ [ -z xterm ]
+ _init_erts_config
+ [ -z 8.2 ]
+ __erts_dir=/srv/apps/flowmail_web/erts-8.2
+ [ -d /srv/apps/flowmail_web/erts-8.2 ]
+ export ROOTDIR=/srv/apps/flowmail_web
+ export ERTS_DIR=/srv/apps/flowmail_web/erts-8.2
+ [ -z /srv/apps/flowmail_web ]
+ mkdir -p /srv/apps/flowmail_web/var
+ echo Files in this directory are regenerated frequently, edits will be lost
+ mkdir -p /srv/apps/flowmail_web/var/log
+ _init_configs
+ [ -z /srv/apps/flowmail_web/var/vm.args ]
+ export SRC_VMARGS_PATH=/srv/apps/flowmail_web/var/vm.args
+ [ /srv/apps/flowmail_web/var/vm.args != /srv/apps/flowmail_web/var/vm.args ]
+ [ ! -z true ]
+ _replace_os_vars /srv/apps/flowmail_web/var/vm.args
+ awk 
        function escape(s) {
            gsub(/&/, "\\\\&", s);
            return s;
        }
        {
            while(match($0,"[$]{[^}]*}")) {
                var=substr($0,RSTART+2,RLENGTH-3);
                gsub("[$]{"var"}", escape(ENVIRON[var]))
            }
        }1
+ mv -- /srv/apps/flowmail_web/var/vm.args.bak /srv/apps/flowmail_web/var/vm.args
mv: cannot stat '/srv/apps/flowmail_web/var/vm.args.bak': No such file or directory
```

**Comment by bitwalker** [comment] 2017-06-22 18:24
The problem is occuring in `_replace_os_vars` - the `awk` command is apparently failing to write to the backup file, that almost certainly has to be a permissions thing. Can you poke around with that function and see if you can determine what might be going on there? The OS you are using may have something to do with it as well (due to some OSes "emulating" `sh` rather than actually running `sh` or `bash` in `sh` mode - Ubuntu being one of them, as it uses `dash`). It could be that the piping happening there is not supported in the shell it's running under.

**Comment by lessless** [comment] 2017-06-23 03:53
@bitwalker Indeed, the os is Ubuntu 16.04.

I took the `_replace_os_vars` code until the point it fails (without `mv` directive) and called it with the sample `vm.args` file. The function created `vm.args.bak` with the expanded environment variables in it:

```
$ ls
replace_os_vars.sh  vm.args
$ cat vm.args
${LESSOPEN}
LESSOPEN
$ _replace_os_vars vm.args
$ cat vm.args.bak
| /usr/bin/lesspipe %s
LESSOPEN
$ type _replace_os_vars
_replace_os_vars is a function
_replace_os_vars ()
{
    awk '
        function escape(s) {
            gsub(/'\&'/, "\\\\&", s);
            return s;
        }
        {
            while(match($0,"[$]{[^}]*}")) {
                var=substr($0,RSTART+2,RLENGTH-3);
                gsub("[$]{"var"}", escape(ENVIRON[var]))
            }
        }1' < "$1" > "$1.bak"
}
```

This is the same account that we are using for deploy

**Comment by bitwalker** [comment] 2017-06-28 20:21
Huh, this one is hiding really well. I wonder if the issue has anything to do with symlinking, as I know edeliver does some of that and it's the only thing I can see that differs in a meaningful way, could you see what happens when `vm.args` is a symlink to another file? I really need to take a deeper look at edeliver as I've seen a number of issues come through which seem to be related to using it (not that edeliver is necessarily doing bad things, just that it could be violating some invariants I'm assuming are true in distillery deployments).

**Comment by lessless** [comment] 2017-06-29 10:32
done, looks like there are no problems with symlink on the file operations level.

before:

```
$ mv vm.args real.vm.args
$ ln -sf real.vm.args vm.args
$ ls -l
total 20
drwxrwxr-x 3 deploy deploy 4096 May 11 22:42 erl_pipes
drwxrwxr-x 2 deploy deploy 4096 Jun 29 03:38 log
-rw-rw-r-- 1 deploy deploy  618 Jun 29 03:38 real.vm.args
-rw-rw-r-- 1 deploy deploy 3313 Jun 29 03:38 sys.config
lrwxrwxrwx 1 deploy deploy   12 Jun 29 04:59 vm.args -> real.vm.args
-rw-rw-r-- 1 deploy deploy   71 Jun 29 03:38 WARNING_README
```

after
```
$ ls -l
total 24
drwxrwxr-x 3 deploy deploy 4096 May 11 22:42 erl_pipes
drwxrwxr-x 2 deploy deploy 4096 Jun 29 03:38 log
-rw-rw-r-- 1 deploy deploy  618 Jun 29 04:59 real.vm.args
-rw-rw-r-- 1 deploy deploy 3313 Jun 29 05:25 sys.config
-rw-rw-r-- 1 deploy deploy  618 Jun 29 05:25 vm.args
-rw-rw-r-- 1 deploy deploy   71 Jun 29 05:25 WARNING_README
```

The fun part is that node wasn't started, but I'm not sure if it's related to the distillery or to the edeliver:

```
+ export DISTILLERY_TASK=rpcterms
+ _check_cookie
+ [ -z XR...{ ]
+ [ -z XR...{ ]
+ nodetool ping
+ command=ping
+ shift
+ name=app_name@127.0.0.1
+ /srv/apps/app_name/erts-8.2/bin/escript /srv/apps/app_name/bin/nodetool -name app_name@127.0.0.1 -setcookie XR...{ ping
+ echo Node is not running!
+ exit 1
```

**Comment by bitwalker** [comment] 2017-06-30 16:51
Are you only seeing this when running with edeliver or does it happen even with the raw Distillery script? I'm trying to figure out how to reproduce this for myself so I don't have to keep bugging you to do stuff for me, but so far I haven't been able to do so (I haven't gone down the route of trying to replicate everything including edeliver, but that's mostly because I was hoping we could repro without that in the mix)

**Comment by lessless** [comment] 2017-07-01 00:59
It never happened during `bin/app_name` script execution, if you're asking about that.  I can give you access to the staging if it will not be abuse of your time.

**Comment by bitwalker** [comment] 2017-07-01 17:24
Yeah I'm talking about the `bin/app` script, so that's good to know. I'll take a look at edeliver to see if I can find anything out just by reading how it executes the boot script, if that fails to lead anywhere, then we can try to coordinate a time to look at your staging environment.

**Comment by bitwalker** [comment] 2017-07-01 17:27
Can you provide me with your edeliver config? Feel free to obfuscate anything sensitive. You can send it to my email as well (it's in my GitHub profile), if you're more comfortable with that.

**Comment by bitwalker** [comment] 2017-07-01 18:02
Based on my reading of edeliver so far, the one thing I'm suspicious of is the `LINK_*` variables you can set which modify the release tarball to contain symlinks to `vm.args` and `sys.config`. I'm not yet sure what gets linked to what, so I'll probably have to spin up a little test with edeliver to see if I can repro. That said, if you aren't using those settings, it must be something else, but I am suspicious that it could be a permissions thing too.

**Comment by lessless** [comment] 2017-07-06 08:42
We are definitely not using symlinks consciously and there is no any `LINK_` variables set.
There was same error message for the `sys.config.bak` today:
`mv: cannot stat '/.../var/sys.config.bak': No such file or directory`

I'm not sure if it is related, but we merged two PRs in the master almost in the same time and they might be deployed simultaneously.

**Comment by bitwalker** [comment] 2017-07-06 20:42
Now that's interesting - I could see the deployment of two releases to the same host/location at the same time causing issues. It would certainly explain why files which must exist (because of the code path) are subsequently not found. The trouble is, I'm not sure there is a good way to prevent that from happening. In our own CI environment, builds/deploys are serialized, so there is never more than one deployment taking place at a given time.

The trouble with races like this is how difficult they are to reproduce. Do you think there is a correlation here or is it more coincidence?

**Comment by lessless** [comment] 2017-07-07 05:05
The simultaneous deploy only related to the yesterday situation and I'm looking how to adjust the amount of CI workers for the deployment branches so it won't happen again.
This is just to stress that it also happened with the `sys.config.bak` in a special condition. Hope that can help somehow :)

**Comment by lessless** [comment] 2017-07-07 12:26
@bitwalker observation: `mix edeliver start staging` can't start staging with `mv: cannot stat '/.../app_name/var/vm.args.bak': No such file or directory` but `./bin/app_name start` does the job perfectly!

**Comment by lessless** [comment] 2017-07-13 04:42
Nah, edeliver has nothing to do with it - it just executes `bin/${APP_NAME} start`, and failure also began to arise with `sys.config.bak`, but in the same routine

```
+ awk
        function escape(s) {
            gsub(/&/, "\\\\&", s);
            return s;
        }
        {
            while(match($0,"[$]{[^}]*}")) {
                var=substr($0,RSTART+2,RLENGTH-3);
                gsub("[$]{"var"}", escape(ENVIRON[var]))
            }
        }1
+ mv -- /srv/apps/app_name/var/sys.config.bak /srv/apps/app_name/var/sys.config
mv: cannot stat '/srv/apps/app_name/var/sys.config.bak': No such file or directory
```

**Comment by bitwalker** [comment] 2017-07-13 04:51
@lessless If it only occurs when run under `edeliver`, it certainly has something to do with it ;). Edeliver does quite a bit more than just run the `start` task - it repackages the release and does a number of other things when deploying the release package - none of that seems like a problem to me, but clearly something isn't right.

I have yet to be able to reproduce this unfortunately :(

**Comment by lessless** [comment] 2017-07-24 03:35
A week ago we switched to to hot code upgrade and it works good so far :)

**Comment by bitwalker** [comment] 2017-07-24 05:55
Glad to hear it :)

**Closed** 2017-09-14 19:41 UTC

**Comment by cvortmann** [comment] 2019-02-01 09:42
We just got the same error using:

Distillery: 2.0.12
Elixir: 1.8.0
Erlang/OTP: 21.2.4

We deploy our applications using AWS CodeDeploy, a single application to a single instance, no concurrent deploys. We deploy 4 instances and it only happens in some of them (normally 1 on them).

![screenshot 2019-02-01 at 10 20 44](https://user-images.githubusercontent.com/189174/52114067-61463e80-260b-11e9-97fe-c966c8a84eb4.png)

Here's our whole `appspec.yml`:

```
version: 0.0
os: linux
files:
  - source: marketing_website.tar.gz
    destination: /home/ubuntu
permissions:
  - object: /home/ubuntu
    owner: ubuntu
    group: ubuntu
    type:
      - directory
hooks:
  ApplicationStop:
    - location: scripts/stop.sh
      timeout: 30
      runas: ubuntu
  AfterInstall:
    - location: scripts/decompress-application.sh
      timeout: 30
      runas: ubuntu
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 180
      runas: ubuntu
  ValidateService:
    - location: scripts/verify.sh
      timeout: 30
      runas: ubuntu
```

All files files belong to the same user. Everything goes in to the user's home folder.

And here's what each script do:

`stop.sh`: 

```
#!/usr/bin/env bash
cd /home/ubuntu
./bin/marketing_website stop
```

`decompress-application.sh`: 

```
#!/usr/bin/env bash
cd /home/ubuntu
tar -zxf /home/ubuntu/marketing_website.tar.gz
```

`start.sh`:

```
#!/usr/bin/env bash
cd /home/ubuntu
REPLACE_OS_VARS=true ./bin/marketing_website start
```

`verify.sh`:

```
#!/usr/bin/env bash
cd /home/ubuntu
./bin/marketing_website ping
```

We suspect it has something to do with `REPLACE_OS_VARS` being present only in the `start` script. We're currently trying to reproduce the error using `REPLACE_OS_VARS` in all scripts except `decompress-application.sh`.

----

Having `REPLACE_OS_VARS` in all scripts give another error: 

```
cp: cannot create regular file '/home/ubuntu/var/vm.args.bak': File exists
```

**Comment by cvortmann** [comment] 2019-02-01 09:59
We repackage the package created by `mix release` to include the `appspec.yml` file and the `scripts` folders as such: 

```elixir
System.cmd(
      "tar",
      ~w[
        -czp
        -f
        release/#{name}.tar.gz
        appspec.yml
        scripts/
        -C_build/prod/rel/marketing_website/releases/1.0.0/
        marketing_website.tar.gz
      ]
    )
```

**Comment by cvortmann** [comment] 2019-02-01 10:18
We also sometimes see this error: 

```
could not start kernel pid (application_controller) (error in config file "/home/ubuntu/var/sys.config" (none): no ending <dot> found)
```

But the `sys.config` has a ending `.`. We believe something else is running after and regenerating the `sys.config` file so we can't see what was the `sys.config` that `start` read.
