### ISSUE TITLE
Elixir.Mix.Releases.Config.Provider issue in release

### ISSUE THREAD

**Issue by bjuretic** [bitwalker/distillery#435] opened 2018-07-28 17:52 UTC
Master branch of Distillery used, production release generated for simple app. Elixir 1.7.1. Tried it on osx and from your latest 1.7.1 Alpine Elixir docker container (with build tools added), same issue.

```
$ _build/prod/rel/auth/bin/auth console
Erlang/OTP 21 [erts-10.0.4] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [hipe] [dtrace]

{"init terminating in do_boot",{undef,[{'Elixir.Mix.Releases.Config.Provider',init,[[]],[]},{init,eval_script,2,[]},{init,do_boot,3,[]}]}}
init terminating in do_boot ({undef,[{Elixir.Mix.Releases.Config.Provider,init,[[_]],[]},{init,eval_script,2,[]},{init,do_boot,3,[]}]})
```

Any ideas where to look?

**Comment by bitwalker** [comment] 2018-07-30 16:41
How is your `:distillery` dependency configured in `mix.exs`?

**Comment by bjuretic** [comment] 2018-07-30 19:38
Like this: `{:distillery, "~> 2.0", runtime: false, github: "bitwalker/distillery"}`

**Comment by bitwalker** [comment] 2018-07-31 02:36
Yes, though in master I've made it so that if Distillery sees that it has been decorated with `runtime: false`, it ignores it, and adds itself to the release anyway. Should be fixed, can you confirm with what is in master now?

**Comment by bjuretic** [comment] 2018-07-31 08:18
I've removed `runtime: false`, included ERTS in the release and it works (it does not yet work with ERTS not included because of system library issue from previous ticket).

The only issue is that if you forget to enter config file location in 

` set config_providers: [{Mix.Releases.Config.Providers.Elixir, ["var/config.exs"]}]`
 
then the error is very hard to spot:

```
$ docker run -it --entrypoint "/bin/bash" netbanking/auth:latest
bash-4.4$ bin/auth console
Erlang/OTP 21 [erts-10.0.3] [source] [64-bit] [smp:6:6] [ds:6:6:10] [async-threads:1] [hipe]

{"init terminating in do_boot",{function_clause,[{'Elixir.Mix.Releases.Config.Providers.Elixir',init,[[]],[{file,"lib/mix/lib/releases/config/providers/elixir.ex"},{line,11}]},{'Elixir.Mix.Releases.Config.Provider','-init/1-fun-0-',2,[{file,"lib/mix/lib/releases/config/provider.ex"},{line,92}]},{'Elixir.Enum','-reduce/3-lists^foldl/2-0-',3,[{file,"lib/enum.ex"},{line,1925}]},{'Elixir.Mix.Releases.Config.Provider',init,1,[{file,"lib/mix/lib/releases/config/provider.ex"},{line,84}]},{init,eval_script,2,[]},{init,do_boot,3,[]}]}}
init terminating in do_boot ({function_clause,[{Elixir.Mix.Releases.Config.Providers.Elixir,init,[[_]],[{_},{_}]},{Elixir.Mix.Releases.Config.Provider,-init/1-fun-0-,2,[{_},{_}]},{Elixir.Enum,-reduce/
```

So maybe this error case should be handled and raised with a nice error message.

**Closed** 2018-07-31 13:41 UTC
Labels: bug, deployment:config-providers, fixed

**Comment by djthread** [comment] 2018-08-29 01:41
I am stuck with this one! I depend on distillery with `{:distillery, "~> 2.0"}`, I `set include_erts: true` for the prod environment I'm building a release for... `make build` succeeds, but `make run` gives me this:

```
$ make run
docker run --env-file config/docker.env \
		--expose 4000 -p 4000:4000 \
		--rm -it `grep 'app:' mix.exs | sed -e 's/\[//g' -e 's/ //g' -e 's/app://' -e 's/[:,]//g'`:latest
init terminating in do_boot ({,[{Elixir.Mix.Releases.Config.Providers.Elixir,init,[],[{_},{_}]},{Elixir.Mix.Releases.Config.Provider,-init/1-fun-0-,2,[{_},{_}]},{Elixir.Enum,-reduce/3-lists^foldl/2-0-

Crash dump is being written to: erl_crash.dump...done
Unable to configure release!
make: *** [run] Error 1
```

Here's what I've got:https://github.com/djthread/powerbot

Thank you so much for your hard work, Paul. I've been using 1.x for years.

**Comment by bitwalker** [comment] 2018-08-29 02:56
@djthread The problem is that you need to wrap the path in a list, i.e. `{Mix.Releases.Config.Providers.Elixir, ["${RELEASE_ROOT_DIR}/etc/config.exs"]}`. This was an error in the docs, but it has been fixed in master, I just haven't updated them yet. Sorry for the confusion!
