### ISSUE TITLE
Cannot add file sys.config to tar file, `mix release  --env=prod` fails

### ISSUE THREAD

**Issue by 1zaak** [bitwalker/distillery#185] opened 2017-01-15 04:40 UTC
My setup is based on [these steps.](https://dennisreimann.de/articles/phoenix-deployment-gatling-ubuntu-digital-ocean.html?utm_source=elixirdigest&utm_medium=email&utm_campaign=featured)

After setting up everything based on the steps above, i ran `npm install` and proceed to run all 3 commands from the [Building The Release](https://hexdocs.pm/distillery/use-with-phoenix.html#building-your-release) section. But, the third step fails and produce this error:

### Verbose Logs
```
==> Loading configuration..
==> Assembling release..
==> Building release msqh_portal:0.2.0 using environment prod
==> One or more direct or transitive dependencies are missing from
    :applications or :included_applications, they will not be included
    in the release:

    :misc_random

    This can cause your application to fail at runtime. If you are sure
    that this is not an issue, you may ignore this warning.

==> Discovered applications:
  distillery-1.1.0
    from: _build/prod/lib/distillery
    applications:
      :kernel
      :stdlib
      :elixir
    includes: none

  porcelain-2.0.3
    from: _build/prod/lib/porcelain
    applications:
      :kernel
      :stdlib
      :elixir
      :logger
      :crypto
    includes: none

  pdf_generator-0.3.5
    from: _build/prod/lib/pdf_generator
    applications:
      :kernel
      :stdlib
      :elixir
      :logger
      :porcelain
    includes: none

  calendar-0.16.1
    from: _build/prod/lib/calendar
    applications:
      :kernel
      :stdlib
      :elixir
      :logger
      :tzdata
    includes: none

  quantum-1.8.1
    from: _build/prod/lib/quantum
    applications:
      :kernel
      :stdlib
      :elixir
      :calendar
    includes: none

  eredis-1.0.8
    from: _build/prod/lib/eredis
    applications:
      :kernel
      :stdlib
    includes: none

  exredis-0.2.5
    from: _build/prod/lib/exredis
    applications:
      :kernel
      :stdlib
      :elixir
      :eredis
    includes: none

  uuid-1.1.5
    from: _build/prod/lib/uuid
    applications:
      :kernel
      :stdlib
      :elixir
    includes: none

  toniq-1.2.0
    from: _build/prod/lib/toniq
    applications:
      :kernel
      :stdlib
      :elixir
      :logger
      :uuid
      :exredis
    includes: none

  timex_ecto-3.0.5
    from: _build/prod/lib/timex_ecto
    applications:
      :kernel
      :stdlib
      :elixir
      :logger
      :ecto
      :timex
    includes: none

  combine-0.9.3
    from: _build/prod/lib/combine
    applications:
      :kernel
      :stdlib
      :elixir
    includes: none

  tzdata-0.5.9
    from: _build/prod/lib/tzdata
    applications:
      :kernel
      :stdlib
      :elixir
      :hackney
      :logger
    includes: none

  timex-3.1.5
    from: _build/prod/lib/timex
    applications:
      :kernel
      :stdlib
      :elixir
      :logger
      :tzdata
      :gettext
      :combine
    includes: none

  scrivener_html-1.4.0
    from: _build/prod/lib/scrivener_html
    applications:
      :kernel
      :stdlib
      :elixir
      :logger
    includes: none

  scrivener_ecto-1.0.3
    from: _build/prod/lib/scrivener_ecto
    applications:
      :kernel
      :stdlib
      :elixir
      :scrivener
      :logger
    includes: none

  gen_smtp-0.11.0
    from: _build/prod/lib/gen_smtp
    applications:
      :kernel
      :stdlib
      :crypto
      :asn1
      :public_key
      :ssl
    includes: none

  bamboo_smtp-1.2.1
    from: _build/prod/lib/bamboo_smtp
    applications:
      :kernel
      :stdlib
      :elixir
      :gen_smtp
      :logger
      :bamboo
    includes: none

  bamboo-0.7.0
    from: _build/prod/lib/bamboo
    applications:
      :kernel
      :stdlib
      :elixir
      :logger
      :httpoison
      :poison
    includes: none

  arc_ecto-0.5.0
    from: _build/prod/lib/arc_ecto
    applications:
      :kernel
      :stdlib
      :elixir
      :logger
    includes: none

  metrics-1.0.1
    from: _build/prod/lib/metrics
    applications:
      :kernel
      :stdlib
    includes: none

  ssl_verify_fun-1.1.1
    from: _build/prod/lib/ssl_verify_fun
    applications:
      :kernel
      :stdlib
      :ssl
    includes: none

  certifi-0.7.0
    from: _build/prod/lib/certifi
    applications:
      :kernel
      :stdlib
    includes: none

  mimerl-1.0.2
    from: _build/prod/lib/mimerl
    applications:
      :kernel
      :stdlib
    includes: none

  idna-1.2.0
    from: _build/prod/lib/idna
    applications:
      :kernel
      :stdlib
    includes: none

  ssl-8.1
    from: /usr/lib/erlang/lib/ssl-8.1
    applications:
      :crypto
      :public_key
      :kernel
      :stdlib
    includes: none

  public_key-1.3
    from: /usr/lib/erlang/lib/public_key-1.3
    applications:
      :asn1
      :crypto
      :kernel
      :stdlib
    includes: none

  asn1-4.0.4
    from: /usr/lib/erlang/lib/asn1-4.0.4
    applications:
      :kernel
      :stdlib
    includes: none

  hackney-1.6.5
    from: _build/prod/lib/hackney
    applications:
      :kernel
      :stdlib
      :crypto
      :asn1
      :public_key
      :ssl
      :idna
      :mimerl
      :certifi
      :ssl_verify_fun
      :metrics
    includes: none

  httpoison-0.11.0
    from: _build/prod/lib/httpoison
    applications:
      :kernel
      :stdlib
      :elixir
      :hackney
    includes: none

  arc-0.6.0
    from: _build/prod/lib/arc
    applications:
      :kernel
      :stdlib
      :elixir
      :logger
      :httpoison
    includes: none

  scrivener-2.1.1
    from: _build/prod/lib/scrivener
    applications:
      :kernel
      :stdlib
      :elixir
      :logger
    includes: none

  money-1.2.0
    from: _build/prod/lib/money
    applications:
      :kernel
      :stdlib
      :elixir
    includes: none

  comeonin-2.6.0
    from: _build/prod/lib/comeonin
    applications:
      :kernel
      :stdlib
      :elixir
      :crypto
      :logger
    includes: none

  connection-1.0.4
    from: _build/prod/lib/connection
    applications:
      :kernel
      :stdlib
      :elixir
    includes: none

  db_connection-1.1.0
    from: _build/prod/lib/db_connection
    applications:
      :kernel
      :stdlib
      :elixir
      :logger
      :connection
    includes: none

  postgrex-0.12.1
    from: _build/prod/lib/postgrex
    applications:
      :kernel
      :stdlib
      :elixir
      :logger
      :db_connection
      :decimal
    includes: none

  poolboy-1.5.1
    from: _build/prod/lib/poolboy
    applications:
      :kernel
      :stdlib
    includes: none

  decimal-1.3.1
    from: _build/prod/lib/decimal
    applications:
      :kernel
      :stdlib
      :elixir
    includes: none

  ecto-2.0.6
    from: _build/prod/lib/ecto
    applications:
      :kernel
      :stdlib
      :elixir
      :logger
      :decimal
      :poolboy
    includes: none

  phoenix_ecto-3.0.1
    from: _build/prod/lib/phoenix_ecto
    applications:
      :kernel
      :stdlib
      :elixir
      :logger
      :ecto
      :plug
    includes: none

  gettext-0.13.0
    from: _build/prod/lib/gettext
    applications:
      :kernel
      :stdlib
      :elixir
      :logger
    includes: none

  cowlib-1.0.2
    from: _build/prod/lib/cowlib
    applications:
      :kernel
      :stdlib
      :crypto
    includes: none

  ranch-1.2.1
    from: _build/prod/lib/ranch
    applications:
      :kernel
      :stdlib
    includes: none

  cowboy-1.0.4
    from: _build/prod/lib/cowboy
    applications:
      :kernel
      :stdlib
      :ranch
      :cowlib
      :crypto
    includes: none

  phoenix_html-2.9.1
    from: _build/prod/lib/phoenix_html
    applications:
      :kernel
      :stdlib
      :elixir
      :logger
      :plug
    includes: none

  phoenix_pubsub-1.0.1
    from: _build/prod/lib/phoenix_pubsub
    applications:
      :kernel
      :stdlib
      :elixir
      :logger
      :crypto
    includes: none

  eex-1.4.0
    from: /usr/local/lib/elixir/bin/../lib/eex
    applications:
      :kernel
      :stdlib
      :elixir
    includes: none

  poison-2.2.0
    from: _build/prod/lib/poison
    applications:
      :kernel
      :stdlib
      :elixir
    includes: none

  mime-1.0.1
    from: _build/prod/lib/mime
    applications:
      :kernel
      :stdlib
      :elixir
    includes: none

  logger-1.4.0
    from: /usr/local/lib/elixir/bin/../lib/logger
    applications:
      :kernel
      :stdlib
      :elixir
    includes: none

  crypto-3.7.2
    from: /usr/lib/erlang/lib/crypto-3.7.2
    applications:
      :kernel
      :stdlib
    includes: none

  plug-1.3.0
    from: _build/prod/lib/plug
    applications:
      :kernel
      :stdlib
      :elixir
      :crypto
      :logger
      :mime
    includes: none

  phoenix-1.2.1
    from: _build/prod/lib/phoenix
    applications:
      :kernel
      :stdlib
      :elixir
      :plug
      :poison
      :logger
      :eex
    includes: none

  compiler-7.0.3
    from: /usr/lib/erlang/lib/compiler-7.0.3
    applications:
      :kernel
      :stdlib
    includes: none

  elixir-1.4.0
    from: /usr/local/lib/elixir/bin/../lib/elixir
    applications:
      :kernel
      :stdlib
      :compiler
    includes: none

  stdlib-3.2
    from: /usr/lib/erlang/lib/stdlib-3.2
    applications:
      :kernel
    includes: none

  kernel-5.1.1
    from: /usr/lib/erlang/lib/kernel-5.1.1
    applications: none
    includes: none

  msqh_portal-0.2.0
    from: _build/prod/lib/msqh_portal
    applications:
      :kernel
      :stdlib
      :elixir
      :phoenix
      :phoenix_pubsub
      :phoenix_html
      :cowboy
      :logger
      :gettext
      :phoenix_ecto
      :postgrex
      :comeonin
      :money
      :scrivener
      :arc
      :arc_ecto
      :bamboo
      :bamboo_smtp
      :scrivener_ecto
      :scrivener_html
      :timex
      :timex_ecto
      :toniq
      :quantum
      :calendar
      :pdf_generator
      :distillery
    includes: none

  iex-1.4.0
    from: /usr/local/lib/elixir/bin/../lib/iex
    applications:
      :kernel
      :stdlib
      :elixir
    includes: none

  sasl-3.0.2
    from: /usr/lib/erlang/lib/sasl-3.0.2
    applications:
      :kernel
      :stdlib
    includes: none

==> Generated overlay vars:
    release_name=:msqh_portal
    release_version="0.2.0"
    is_upgrade=false
    upgrade_from=:latest
    dev_mode=false
    include_erts=true
    include_src=false
    include_system_libs=true
    erl_opts=""
    erts_vsn="8.2"
    output_dir="rel/msqhportal"
==> Copying applications to rel/msqhportal
==> Generating nodetool
==> Generating start_erl.data
==> Generating vm.args
==> Generating sys.config from config/config.exs
==> Including ERTS 8.2 from /usr/lib/erlang/erts-8.2
==> Generating boot script
==> Generating RELEASES
==> Generating start_clean.boot
==> Applying overlays
==> Applying mkdir overlay
    dst: releases/0.2.0/hooks
==> Applying mkdir overlay
    dst: releases/0.2.0/hooks/pre_start.d
==> Applying mkdir overlay
    dst: releases/0.2.0/hooks/post_start.d
==> Applying mkdir overlay
    dst: releases/0.2.0/hooks/pre_stop.d
==> Applying mkdir overlay
    dst: releases/0.2.0/hooks/post_stop.d
==> Applying mkdir overlay
    dst: releases/0.2.0/hooks/pre_upgrade.d
==> Applying mkdir overlay
    dst: releases/0.2.0/hooks/post_upgrade.d
==> Applying mkdir overlay
    dst: releases/0.2.0/commands
==> Packaging release..
==> Archiving msqh_portal-0.2.0
==> Writing tarball to rel/msqhportal/releases/0.2.0/msqh_portal.tar.gz
Cannot add file sys.config to tar file - [{error,{13,erl_parse,["syntax error before: ",["Fun"]]}}]
==> Problem generating release tarball:
    {:tar_generation_error, :unknown}
```

### Description of issue
I'm on a fresh DO Ubuntu 16.04 with Elixir 1.4 (the application is using 1.2)

The `rel/config.exs`:
```
# Import all plugins from `rel/plugins`
# They can then be used by adding `plugin MyPlugin` to
# either an environment, or release definition, where
# `MyPlugin` is the name of the plugin module.
Path.join(["rel", "plugins", "*.exs"])
|> Path.wildcard()
|> Enum.map(&Code.eval_file(&1))

use Mix.Releases.Config,
    # This sets the default release built by `mix release`
    default_release: :default,
    # This sets the default environment used by `mix release`
    default_environment: :prod

# For a full list of config options for both releases
# and environments, visit https://hexdocs.pm/distillery/configuration.html


# You may define one or more environments in this file,
# an environment's settings will override those of a release
# when building in that environment, this combination of release
# and environment configuration is called a profile

environment :dev do
  set dev_mode: true
  set include_erts: false
  set cookie: :"Nz9&9%%ppXil>5yk91;([3JQXx(F.CguWOX`8[>0j&A2y?>*EXk2zU)sBKe1o]>,"
end

environment :prod do
  set include_erts: true
  set include_src: false
  set cookie: :"XfepVx~XzU73I[KF,F4<;oRq?5xZT~YVZh(/sF=cLGE(d!DpR;OYRDIm<zTPIYaV"
  set output_dir: "rel/msqhportal"
end

# You may define one or more releases in this file.
# If you have not set a default release, or selected one
# when running `mix release`, the first release in the file
# will be used by default

release :msqh_portal do
  set version: current_version(:msqh_portal)
end
```

Not sure why this happens as well:
```
==> One or more direct or transitive dependencies are missing from
    :applications or :included_applications, they will not be included
    in the release:

    :misc_random

    This can cause your application to fail at runtime. If you are sure
    that this is not an issue, you may ignore this warning.

```

Thanks in advance.

**Comment by bitwalker** [comment] 2017-01-15 20:01
I suspect the problem is that your `config.exs` contains a function capture somewhere. Could you verify if that's the case? If you are unsure, feel free to paste the config here (with anything sensitive elided), and I can take a look.

**Comment by bitwalker** [comment] 2017-02-04 00:00
ping :)

**Comment by bitwalker** [comment] 2017-02-17 15:37
I'm going to close this for now, feel free to reopen it if you are still having this problem.

**Closed by bitwalker** 2017-02-17 15:37 UTC

**Comment by wanderanimrod** [comment] 2017-03-12 05:04
@bitwalker , I have a function reference in my config and it causes this failure when MIX_ENV=prod.

Unfortunately, I am required by a dependency to use a function for that specific configuration value. Is there any workaround that does not involve removing the function capture? 

Also, why does this work with MIX_ENV=dev and not MIX_ENV=prod?

**Comment by bitwalker** [comment] 2017-03-12 05:52
Which dependency is it? They should take an MFA tuple, rather than a function capture, because it basically makes it a huge pain to use in a release, basically the only way to work around it is to set the start type of the dependency to :load and set up the configuration before starting it, but that can be a whole can of worms depending on what in your application depends on it. I'm willing to help open up a PR to get that fixed, you could then use that patch in the meantime.

**Comment by wanderanimrod** [comment] 2017-03-12 06:01
Thanks for the quick response @bitwalker . It turns out the ex_json_schema recently added the ability to use and MFA tuple precisely because of this limitation. I have used that and managed to proceed. 

Thanks again

**Comment by bitwalker** [comment] 2017-03-12 06:08
Awesome, glad to hear that :)

**Comment by micheleriva** [comment] 2020-08-10 07:46
Hi @bitwalker ,
sorry if I come back to this old issue!

I'm experiencing this exact error while deploying Phoenix to DO.
My `config.exs` file looks like this:

```elixir
use Mix.Config

config :myapp,
  ecto_repos: [MyApp.Repo]

# Configures the endpoint
config :myapp, MyApp.Endpoint,
  url: [host: "localhost"],
  secret_key_base: "<<mysecret>>",
  render_errors: [view: MyApp.ErrorView, accepts: ~w(json)],
  pubsub: [name: MyApp.PubSub, adapter: Phoenix.PubSub.PG2],
  live_view: [signing_salt: "somesalt"]

# Configures Elixir's Logger
config :logger, :console,
  format: "$time $metadata[$level] $message\n",
  metadata: [:request_id]

# Use Jason for JSON parsing in Phoenix
config :phoenix, :json_library, Jason

# Config Goth
config :goth,
  json: "somepath/keyfile.json" |> File.read!()

# Config cron scheduler
config :myapp, MyApp.Scheduler,
  jobs: [
    {"*/5 * * * *", fn -> MyApp.somefunc() end}
  ]

import_config "#{Mix.env()}.exs"
```

and my deliver config looks like this (removes sensitive data such as IP and other stuff):

```sh
APP="myapp"

BUILD_HOST="0.0.0.0"
BUILD_USER="deploy"
BUILD_AT="/tmp/edeliver/$APP/builds"
RELEASE_DIR="/tmp/edeliver/$APP/builds/_build/prod/rel/$APP"

PRODUCTION_HOSTS="0.0.0.0"
PRODUCTION_USER="deploy"
DELIVER_TO="/home/deploy"

pre_erlang_get_and_update_deps() {
  local _prod_secret_path="/home/deploy/prod.secret.exs"
  if [ "$TARGET_MIX_ENV" = "prod" ]; then
    __sync_remote "
      ln -sfn '$_prod_secret_path' '$BUILD_AT/config/prod.secret.exs'
    "
  fi
}

pre_erlang_clean_compile() {
  status "Running phoenix.digest"
  __sync_remote " # runs the commands on the build host
    # [ -f ~/.profile ] && source ~/.profile # load profile (optional)
    source ~/.profile
    # echo \$PATH # check if rbenv is in the path
    set -e # fail if any command fails (recommended)
    cd '$BUILD_AT' # enter the build directory on the build host (required)
    # prepare something
    mkdir -p priv/static # required by the phoenix.digest task

    # run your custom task
    APP='$APP' MIX_ENV='$TARGET_MIX_ENV' $MIX_CMD phx.digest $SILENCE
  "
}
```

any idea on how to fix this?
Thank you so much!

**Comment by Ninigi** [comment] 2021-01-26 23:22
@micheleriva as far as I understand the issue, referencing anonymous functions in your config is what causes the problem.

```elixir
# instead of
config :myapp, MyApp.Scheduler,
  jobs: [
    {"*/5 * * * *", fn -> MyApp.somefunc() end}
  ]
  
  # you can reference the function by name
  config :myapp, MyApp.Scheduler,
  jobs: [
    {"*/5 * * * *",  &MyApp.somefunc/0}
  ]
  
  # or use a MFA (module, funciton, arity) tuple
config :myapp, MyApp.Scheduler,
  jobs: [
    {"*/5 * * * *", {MyApp, :somefunc, []}}
  ]
  ```
  
However, @bitwalker I am not sure I am handling this correct in my case, or if there is a better way to do this:
we have 2 dependencies in our app that pass down configuration options to [Redix](https://github.com/whatyouhide/redix), and part of the configuration is using the return value of `:public_key.pkix_verify_hostname_match_fun(:https)` (which is a function

```elixir
:public_key.pkix_verify_hostname_match_fun(:https)
#=> #Function<5.13117337/2 in :public_key.pkix_verify_hostname_match_fun/1>
```

I did not want to tinker with starting the apps manually, so I wrote a wrapper function `def redis_hostname_match(arg1, arg2), do: :public_key.pkix_verify_hostname_match_fun(:https).(arg1, arg2)` that I could pass in to the config.
Do you think that is a good solution, or will that come back and bite us one day?
